// Subtopic Intelligence Library - Catalog Data
// Auto-generated by generate_sil_catalog.py. Deterministic & Offline Capable.

window.SIL_CATALOG = [
  {
    "gate_id": "MATH-QUAD-EQUATIONS",
    "title": "Quadratic Equations",
    "section_number": 3,
    "domain": "Algebra & Theory of Equations",
    "grade_level": "Grade 9–10",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Leading Coefficient Invariant**: For $ax^2 + bx + c = 0$, $a \\neq 0$ must be explicitly asserted before computing roots, discriminant, or axis of symmetry. If $a = 0$, the equation degrades to a linear relation $bx + c = 0$.",
      "**Radical Non-Negativity Invariant**: The principal square root $\\sqrt{\\Delta}$ is non-negative by definition. In real analysis, $\\Delta \\ge 0$ is required for real roots; $\\sqrt{x^2} = |x|$, not merely $x$.",
      "**Fundamental Theorem of Algebra**: A quadratic polynomial with real or complex coefficients has exactly two roots (counting multiplicity) in $\\mathbb{C}$."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-QUAD-01",
        "atom_type": "CONCEPT",
        "description": "Quadratic polynomial as a parabolic mapping $f(x) = ax^2 + bx + c$ with vertex at $\\left(-\\frac{b}{2a}, -\\frac{D}{4a}\\right)$."
      },
      {
        "atom_id": "ATOM-QUAD-02",
        "atom_type": "RELATION",
        "description": "Vieta's formulas: $\\alpha + \\beta = -\\frac{b}{a}$, $\\alpha\\beta = \\frac{c}{a}$."
      },
      {
        "atom_id": "ATOM-QUAD-03",
        "atom_type": "INVARIANT",
        "description": "Discriminant trichotomy: $D = b^2 - 4ac$. $D > 0 \\iff$ two distinct real roots; $D = 0 \\iff$ coincident real roots; $D < 0 \\iff$ complex conjugate pair roots."
      },
      {
        "atom_id": "ATOM-QUAD-04",
        "atom_type": "PROCEDURE",
        "description": "Symmetric algebraic reduction: expressing $\\alpha^2 + \\beta^2 = (\\alpha+\\beta)^2 - 2\\alpha\\beta$ and $\\alpha^3 + \\beta^3 = (\\alpha+\\beta)^3 - 3\\alpha\\beta(\\alpha+\\beta)$."
      },
      {
        "atom_id": "ATOM-QUAD-05",
        "atom_type": "STRATEGY",
        "description": "Location of roots via composite interval testing:\n  - Both roots greater than $k$: $D \\ge 0$, $-\\frac{b}{2a} > k$, and $a \\cdot f(k) > 0$.\n  - Roots on opposite sides of $k$: $a \\cdot f(k) < 0$ (automatically guarantees $D > 0$)."
      }
    ],
    "misconceptions": [
      {
        "name": "Premature Cancellation of Variable",
        "flawed_action": "Solving $x^2 = 5x$ by dividing both sides by $x \\implies x = 5$.",
        "diagnostic_cue": "Dividing by $x$ assumes $x \\neq 0$, silently destroying root $x = 0$. Factor as $x(x - 5) = 0 \\implies x \\in \\{0, 5\\}$."
      },
      {
        "name": "Omitting Parameter Non-Zero Check",
        "flawed_action": "Stating $(m-2)x^2 + 4x + 1 = 0$ has two roots when $D \\ge 0$.",
        "diagnostic_cue": "If $m = 2$, the equation is $4x + 1 = 0$, having only one root $x = -1/4$. The condition $m \\neq 2$ is an essential independent constraint."
      },
      {
        "name": "Root Location without Axis Position",
        "flawed_action": "For both roots $> k$, only checking $D \\ge 0$ and $af(k) > 0$.",
        "diagnostic_cue": "$af(k) > 0$ holds when both roots are greater than $k$ OR when both roots are less than $k$. The axis condition $-\\frac{b}{2a} > k$ is mandatory to orient the parabola."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-QUAD-01",
        "title": "Incomplete Factoring Frame",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Solve for x: 2x² - 7x + 3 = 0\nStep 1: Identify product ac = [ ___ ] and sum b = [ ___ ]\nStep 2: Find factors p, q such that p·q = ac and p + q = b:\n        p = [ ___ ],  q = [ ___ ]\nStep 3: Split middle term: 2x² - [ ___ ]x - [ ___ ]x + 3 = 0\nStep 4: Group terms: 2x(x - [ ___ ]) - 1(x - [ ___ ]) = 0\nStep 5: Factor out common binomial: (2x - 1)(x - [ ___ ]) = 0\nRoots: x = [ ___ ] or x = [ ___ ]",
        "completion_key": "Step 1: ac = 6, b = -7\nStep 2: p = -6, q = -1\nStep 3: 2x² - 6x - 1x + 3 = 0\nStep 4: 2x(x - 3) - 1(x - 3) = 0\nStep 5: (2x - 1)(x - 3) = 0\nRoots: x = 1/2, x = 3"
      },
      {
        "ttu_id": "TTU-QUAD-02",
        "title": "Parabolic Location-of-Roots Geometric Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-4, 6], y ∈ [-5, 10]",
        "scaffold": "Condition Checklist:\n1. Real roots exist:              D = 4(k-1)² - 4(k+5) ≥ 0   ==> k ∈ [ ___ , ___ ] ∪ [ ___ , ___ ]\n2. Axis of symmetry to the right: -b/(2a) = (k-1) > 2        ==> k > [ ___ ]\n3. Function value at boundary:    f(2) = 4 - 4(k-1) + (k+5) > 0 ==> k < [ ___ ]",
        "completion_key": "1. 4(k² - 2k + 1 - k - 5) = 4(k² - 3k - 4) ≥ 0 ==> (k - 4)(k + 1) ≥ 0 ==> k ≤ -1 or k ≥ 4\n2. k - 1 > 2 ==> k > 3\n3. 4 - 4k + 4 + k + 5 = 13 - 3k > 0 ==> 3k < 13 ==> k < 13/3 (4.33)\nIntersection: (k ≤ -1 or k ≥ 4) ∩ (k > 3) ∩ (k < 13/3)\nResult: k ∈ [4, 13/3)"
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-QUAD-01",
        "tier": "Foundation / CBSE",
        "description": "Standard algebraic factoring, discriminant classification, and quadratic formula application."
      },
      {
        "family_id": "FAMILY-QUAD-02",
        "tier": "Olympiad / IOQM",
        "description": "Nonlinear symmetric systems, Newton's sums (S_n = α^n + β^n satisfying a·S_n + b·S_{n-1} + c·S_{n-2} = 0),\n  and integer root constraints via discriminant perfect square analysis."
      },
      {
        "family_id": "FAMILY-QUAD-03",
        "tier": "JEE Main",
        "description": "Quadratic inequalities with sign charts, common root condition (determinant eliminant method),\n  and equations reducible to quadratics via substitution (e.g. t = x + 1/x)."
      },
      {
        "family_id": "FAMILY-QUAD-04",
        "tier": "JEE Advanced",
        "description": "Parametric root location intervals, modulus and logarithmic quadratics, and simultaneous\n  extremum analysis combining calculus with discriminant geometry."
      }
    ]
  },
  {
    "gate_id": "MATH-LIN-EQUATIONS",
    "title": "Linear Systems & Consistency Criteria",
    "section_number": 4,
    "domain": "Algebra & Linear Systems",
    "grade_level": "Grade 9–10",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Non-Degenerate Variable Constraint**: For each equation $a_i x + b_i y + c_i = 0$, the coefficient vector $(a_i, b_i) \\neq (0, 0)$ must hold. A relation with $a_i = b_i = 0$ is either a contradiction ($c_i \\neq 0 \\implies 0 = 1$) or a trivial identity ($c_i = 0$).",
      "**Non-Zero Divisor Invariant in Ratio Form**: Direct comparison $\\frac{a_1}{a_2} = \\frac{b_1}{b_2} = \\frac{c_1}{c_2}$ is valid only if $a_2, b_2, c_2 \\neq 0$. In general, cross-multiplication determinant forms ($a_1 b_2 - a_2 b_1 = 0$, etc.) must be evaluated to prevent division by zero.",
      "**Solvability Invariant (Rouché-Capelli Theorem)**: A system $\\mathbf{A}\\mathbf{x} = \\mathbf{b}$ is consistent if and only if $\\operatorname{rank}(\\mathbf{A}) = \\operatorname{rank}([\\mathbf{A}|\\mathbf{b}])$."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-LIN-01",
        "atom_type": "CONCEPT",
        "description": "Linear equation in two variables as an infinite set of ordered pairs $(x, y) \\in \\mathbb{R}^2$ geometrically forming a Euclidean straight line."
      },
      {
        "atom_id": "ATOM-LIN-02",
        "atom_type": "RELATION",
        "description": "Consistency classification trichotomy:\n  - *Unique solution* (consistent & independent, intersecting lines) $\\iff \\frac{a_1}{a_2} \\neq \\frac{b_1}{b_2} \\iff a_1 b_2 - a_2 b_1 \\neq 0$.\n  - *Infinitely many solutions* (consistent & dependent, coincident lines) $\\iff \\frac{a_1}{a_2} = \\frac{b_1}{b_2} = \\frac{c_1}{c_2}$.\n  - *No solution* (inconsistent, distinct parallel lines) $\\iff \\frac{a_1}{a_2} = \\frac{b_1}{b_2} \\neq \\frac{c_1}{c_2}$."
      },
      {
        "atom_id": "ATOM-LIN-03",
        "atom_type": "PROCEDURE",
        "description": "Algebraic resolution algorithms:\n  - Substitution method: isolating one variable and evaluating univariate equation.\n  - Elimination by equating coefficients: multiplying by suitable scale factors to cancel one variable.\n  - Determinant / Cross-multiplication method: $x = \\frac{b_1 c_2 - b_2 c_1}{a_1 b_2 - a_2 b_1}, y = \\frac{c_1 a_2 - c_2 a_1}{a_1 b_2 - a_2 b_1}$ where $a_1 b_2 - a_2 b_1 \\neq 0$."
      },
      {
        "atom_id": "ATOM-LIN-04",
        "atom_type": "STRATEGY",
        "description": "Rational substitution for reducible nonlinear systems: mapping $u = \\frac{1}{x+y}, v = \\frac{1}{x-y}$ subject to domain constraints $x \\neq \\pm y$."
      },
      {
        "atom_id": "ATOM-LIN-05",
        "atom_type": "INVARIANT",
        "description": "Homogeneous linear systems $a_1 x + b_1 y = 0, a_2 x + b_2 y = 0$ always possess the trivial solution $(0, 0)$; non-trivial solutions exist if and only if determinant $D = a_1 b_2 - a_2 b_1 = 0$."
      }
    ],
    "misconceptions": [
      {
        "name": "Blind Ratio Division with Zero Coefficients",
        "flawed_action": "Evaluating consistency of $3x + 0y = 6$ and $6x + 0y = 12$ by computing $\\frac{a_1}{a_2} = \\frac{3}{6} = \\frac{1}{2}$, and concluding system is undefined because $\\frac{b_1}{b_2} = \\frac{0}{0}$.",
        "diagnostic_cue": "Coefficient ratios are a shorthand for the cross-product determinant. Because $a_1 b_2 - a_2 b_1 = 3(0) - 6(0) = 0$ and $b_1 c_2 - b_2 c_1 = 0(-12) - 0(-6) = 0$, both lines represent the identical vertical line $x = 2$, yielding infinitely many solutions."
      },
      {
        "name": "Inconsistent vs Coincident Confusion",
        "flawed_action": "Concluding a system has no solution whenever $\\frac{a_1}{a_2} = \\frac{b_1}{b_2}$, ignoring the constant ratio $\\frac{c_1}{c_2}$.",
        "diagnostic_cue": "Parallel slope only establishes identical orientation; the lines coincide (infinitely many solutions) if $\\frac{c_1}{c_2}$ equals the slope ratio, and are parallel (no solution) only if $\\frac{c_1}{c_2}$ differs."
      },
      {
        "name": "Unchecked Rational Substitution Domains",
        "flawed_action": "In solving $\\frac{10}{x+y} + \\frac{2}{x-y} = 4$, finding $x=3, y=3$ and accepting it without verification.",
        "diagnostic_cue": "If $x = y = 3$, $x - y = 0$, causing division by zero in the original ground truth equation. All candidates must be checked against domain preconditions."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-LIN-01",
        "title": "Incomplete Algebraic Elimination Frame",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Solve the linear system by elimination:\n  (1)  3x + 4y = 10\n  (2)  2x - 3y = 1\n\nStep 1: Choose variable to eliminate: [ y ]\nStep 2: Find LCM of coefficients of y: LCM(4, 3) = [ ___ ]\nStep 3: Multiply equation (1) by [ ___ ]:  9x + 12y = [ ___ ]   ... (3)\nStep 4: Multiply equation (2) by [ ___ ]:  8x - 12y = [ ___ ]   ... (4)\nStep 5: Add equations (3) and (4):\n        (9x + 8x) + (12y - 12y) = [ ___ ] + [ ___ ]\n        [ ___ ]x = [ ___ ]\n        x = [ ___ ]\nStep 6: Substitute x into equation (1):\n        3([ ___ ]) + 4y = 10  ==>  [ ___ ] + 4y = 10  ==>  4y = [ ___ ]  ==>  y = [ ___ ]\nSolution Pair: (x, y) = ([ ___ ], [ ___ ])",
        "completion_key": "Step 2: LCM = 12\nStep 3: Multiply (1) by 3: 9x + 12y = 30\nStep 4: Multiply (2) by 4: 8x - 12y = 4\nStep 5: 17x = 34 ==> x = 2\nStep 6: 3(2) + 4y = 10 ==> 6 + 4y = 10 ==> 4y = 4 ==> y = 1\nSolution Pair: (x, y) = (2, 1)"
      },
      {
        "ttu_id": "TTU-LIN-02",
        "title": "Parameter Consistency Invariant Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Consistency Conditions for Coincident Lines:\n  a1 / a2 = b1 / b2 = c1 / c2\n  (k - 1) / 6 = 3 / (k + 2) = 2 / k\n\nStep 1: Solve determinant equation D = (k - 1)(k + 2) - 18 = 0\n        k² + k - 2 - 18 = 0  ==>  k² + k - 20 = 0\n        Factors: (k - [ ___ ])(k + [ ___ ]) = 0  ==>  k ∈ { [ ___ ], [ ___ ] }\n\nStep 2: Test candidate k = 4 against constant ratio:\n        a1/a2 = (4-1)/6 = 3/6 = 1/2\n        b1/b2 = 3/(4+2) = 3/6 = 1/2\n        c1/c2 = 2/4 = 1/2\n        Is k = 4 valid? [ YES / NO ]\n\nStep 3: Test candidate k = -5 against constant ratio:\n        a1/a2 = (-5-1)/6 = -6/6 = -1\n        b1/b2 = 3/(-5+2) = 3/(-3) = -1\n        c1/c2 = 2/(-5) = -2/5\n        Does -1 = -2/5? [ YES / NO ] ==> k = -5 yields: [ NO SOLUTION / INFINITE SOLUTIONS ]",
        "completion_key": "Step 1: (k - 4)(k + 5) = 0 ==> k ∈ { 4, -5 }\nStep 2: All three ratios equal 1/2. k = 4 produces coincident lines (YES).\nStep 3: -1 ≠ -2/5. k = -5 produces parallel lines with NO solution.\nConclusion: Unique parameter for infinitely many solutions is k = 4."
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-LIN-01",
        "tier": "Foundation / CBSE",
        "description": "Two-variable elimination and substitution, graphical intersection points, upstream/downstream and fraction modeling."
      },
      {
        "family_id": "FAMILY-LIN-02",
        "tier": "Olympiad / IOQM",
        "description": "Linear Diophantine equations ax + by = c with integer solutions via Euclidean algorithm, Bézout's identity,\n  and non-negative integer lattice point counting."
      },
      {
        "family_id": "FAMILY-LIN-03",
        "tier": "JEE Main",
        "description": "3-variable systems via Cramer's Rule (Δ, Δx, Δy, Δz), parameter intervals for unique vs non-trivial solutions,\n  and homogeneous systems."
      },
      {
        "family_id": "FAMILY-LIN-04",
        "tier": "JEE Advanced",
        "description": "Matrix rank deficiency, geometric planes intersecting in a line vs parallel planes, and parametric\n  vector line representations in R³."
      }
    ]
  },
  {
    "gate_id": "MATH-GEO-TRIANGLES",
    "title": "Triangles, Similarity & Thales' Theorem",
    "section_number": 5,
    "domain": "Euclidean Geometry & Triangles",
    "grade_level": "Grade 9–10",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Strict Triangle Inequality Invariant**: For three non-collinear vertices $A, B, C$, $AB + BC > AC$, $BC + CA > AB$, and $CA + AB > BC$ strictly. Equality implies collinear degenerate line segment with zero enclosed area ($\\operatorname{Area}(\\triangle ABC) = 0$).",
      "**Angle Sum Invariant in Euclidean Metric**: $\\angle A + \\angle B + \\angle C = 180^\\circ$ ($\\pi$ radians).",
      "**Parallel Transversal Ratio Preservation (Thales' Axiom)**: If line $l \\parallel BC$ intersects $AB$ at $D$ and $AC$ at $E$, then $\\frac{AD}{DB} = \\frac{AE}{EC}$."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-TRI-01",
        "atom_type": "CONCEPT",
        "description": "Dilation and similarity: Two triangles $\\triangle ABC$ and $\\triangle DEF$ are similar ($\\triangle ABC \\sim \\triangle DEF$) if and only if corresponding angles are equal ($\\angle A = \\angle D, \\angle B = \\angle E, \\angle C = \\angle F$) and corresponding sides are in a constant proportion $k = \\frac{AB}{DE} = \\frac{BC}{EF} = \\frac{CA}{FD}$."
      },
      {
        "atom_id": "ATOM-TRI-02",
        "atom_type": "INVARIANT",
        "description": "Basic Proportionality Theorem (Thales' Theorem) and its converse: A line drawn parallel to one side of a triangle divides the other two sides in the same ratio; conversely, proportional division implies parallelism."
      },
      {
        "atom_id": "ATOM-TRI-03",
        "atom_type": "RELATION",
        "description": "Internal Angle Bisector Theorem: An interior angle bisector of a triangle divides the opposite side internally in the ratio of the adjacent sides containing the angle: $\\frac{BD}{DC} = \\frac{AB}{AC}$."
      },
      {
        "atom_id": "ATOM-TRI-04",
        "atom_type": "PROCEDURE",
        "description": "Quadratic area scaling: If $\\triangle ABC \\sim \\triangle DEF$ with scale factor $k$, then $\\frac{\\operatorname{Area}(\\triangle ABC)}{\\operatorname{Area}(\\triangle DEF)} = k^2 = \\left(\\frac{AB}{DE}\\right)^2$."
      },
      {
        "atom_id": "ATOM-TRI-05",
        "atom_type": "STRATEGY",
        "description": "Auxiliary construction patterns:\n  - Dropping perpendicular altitudes from common vertices to evaluate area ratios of triangles sharing a common base line.\n  - Constructing parallel auxiliary lines through cevian intersections to transfer segment ratios across multiple triangles (Menelaus and Ceva foundations)."
      }
    ],
    "misconceptions": [
      {
        "name": "Area Ratio Equals Side Ratio",
        "flawed_action": "Stating that if the sides of a triangle are doubled ($k = 2$), its area is also doubled.",
        "diagnostic_cue": "Area is a two-dimensional measure: $\\operatorname{Area} = \\frac{1}{2} \\cdot \\text{base} \\cdot \\text{height}$. Because both base and altitude scale by factor $k$, area scales by $k^2 = 2^2 = 4$."
      },
      {
        "name": "Blind Side Ratios Without Vertex Order Correspondence",
        "flawed_action": "Given $\\triangle ABC \\sim \\triangle DEF$, writing $\\frac{AB}{EF} = \\frac{BC}{DE}$.",
        "diagnostic_cue": "Similarity notation is strictly order-preserving. $\\triangle ABC \\sim \\triangle DEF$ establishes canonical correspondence $A \\leftrightarrow D, B \\leftrightarrow E, C \\leftrightarrow F$. Thus $\\frac{AB}{DE} = \\frac{BC}{EF} = \\frac{CA}{FD}$."
      },
      {
        "name": "Misapplying BPT to Arbitrary Non-Parallel Transversals",
        "flawed_action": "Assuming $\\frac{AD}{DB} = \\frac{AE}{EC}$ holds for any arbitrary transversal segment $DE$.",
        "diagnostic_cue": "BPT strictly requires verified parallelism $DE \\parallel BC$. Without verified parallelism or equiangular orientation, side ratios cannot be equated."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-TRI-01",
        "title": "Incomplete Thales BPT Proof Scaffold",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Theorem: If a line is drawn parallel to one side of a triangle intersecting the other two sides,\n         it divides the two sides in the same ratio.\nGiven: In ΔABC, DE || BC, intersecting AB at D and AC at E.\nTo Prove: AD / DB = AE / EC\n\nConstruction:\n  1. Join BE and [ ___ ].\n  2. Draw altitude DM ⊥ AC and altitude EN ⊥ [ ___ ].\n\nProof Steps:\nStep 1: Area(ΔADE) = 1/2 · base · height = 1/2 · AD · [ ___ ]\nStep 2: Area(ΔBDE) = 1/2 · base · height = 1/2 · DB · [ ___ ]\nStep 3: Ratio (1): Area(ΔADE) / Area(ΔBDE) = (1/2 · AD · EN) / (1/2 · DB · EN) = [ ___ ] / [ ___ ]\n\nStep 4: Similarly, taking base AE and EC with altitude DM:\n        Area(ΔADE) = 1/2 · AE · [ ___ ]\n        Area(ΔCDE) = 1/2 · EC · [ ___ ]\nStep 5: Ratio (2): Area(ΔADE) / Area(ΔCDE) = [ ___ ] / [ ___ ]\n\nStep 6: Geometric Invariant:\n        ΔBDE and ΔCDE are on the same base [ ___ ] and between the same parallel lines [ ___ ] and [ ___ ].\n        Therefore: Area(ΔBDE) = Area([ ___ ])\n\nStep 7: Equating Ratio (1) and Ratio (2):\n        AD / DB = [ ___ ] / [ ___ ]   (Hence Proved)",
        "completion_key": "Construction: 1. Join CD; 2. EN ⊥ AB\nStep 1: EN\nStep 2: EN\nStep 3: AD / DB\nStep 4: DM; DM\nStep 5: AE / EC\nStep 6: Same base DE; parallel lines DE and BC; Area(ΔCDE)\nStep 7: AD / DB = AE / EC"
      },
      {
        "ttu_id": "TTU-TRI-02",
        "title": "Trapezoid Parallel Segment Ratio Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-1, 7], y ∈ [-1, 6]",
        "scaffold": "Step 1: Identify similar triangles:\n        In ΔAOB and ΔCOD:\n        ∠AOB = ∠COD  (Reason: [ _____________________ ])\n        ∠OAB = ∠OCD  (Reason: [ _____________________ ])\n        Therefore, ΔAOB ~ ΔCOD by [ AA / SAS / SSS ] similarity criterion.\n\nStep 2: Formulate corresponding side ratios:\n        AO / CO = BO / [ ___ ] = AB / [ ___ ]\n\nStep 3: Calculate numerical ratio:\n        AO / CO = 12 / [ ___ ] = [ ___ ] / [ ___ ]\n        Ratio AO : OC = [ ___ ] : [ ___ ]",
        "completion_key": "Step 1: Vertically opposite angles; Alternate interior angles (since AB || CD); AA criterion.\nStep 2: DO; CD\nStep 3: 12 / 8 = 3 / 2. Ratio AO : OC = 3 : 2."
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-TRI-01",
        "tier": "Foundation / CBSE",
        "description": "Formal BPT proof, ladder against vertical wall, shadow similarity, and trapezoid diagonal proofs."
      },
      {
        "family_id": "FAMILY-TRI-02",
        "tier": "Olympiad / IOQM",
        "description": "Ceva's Theorem, Menelaus' Theorem on transversals, Stewart's theorem, angle bisector cevian ratios,\n  and spiral similarity under central homothety."
      },
      {
        "family_id": "FAMILY-TRI-03",
        "tier": "JEE Main",
        "description": "Sine rule, cosine rule, projection formula, half-angle formulas, inradius r = Δ/s, and circumradius R = abc/(4Δ)."
      },
      {
        "family_id": "FAMILY-TRI-04",
        "tier": "JEE Advanced",
        "description": "Coordinate and vector geometry synthesis with triangle centers, pedal triangles, distance between\n  incentre and circumcentre (Euler's formula: d² = R² - 2Rr), and extremum area bounds."
      }
    ]
  },
  {
    "gate_id": "MATH-NUM-EUCLID-DIVISION",
    "title": "Number Theory & Euclid's Division Lemma",
    "section_number": 6,
    "domain": "Number Theory & Arithmetic",
    "grade_level": "Grade 9–10",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Strict Divisor Non-Zero Invariant**: In $a = bq + r$, the divisor $b \\neq 0$ must be strictly non-zero. Division by zero is undefined in all rings.",
      "**Strict Remainder Invariant**: The remainder $r$ must satisfy $0 \\le r < |b|$ by definition. Negative remainders or remainders $\\ge |b|$ violate the uniqueness theorem.",
      "**Well-Ordering Principle of $\\mathbb{Z}^+$**: Every non-empty set of positive integers contains a least element. This guarantees the finite termination of the Euclidean algorithm.",
      "**Prime Uniqueness (Fundamental Theorem of Arithmetic)**: Every integer $n > 1$ can be expressed as a product of prime powers $n = p_1^{a_1} p_2^{a_2} \\cdots p_k^{a_k}$ uniquely, up to the order of factors."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-NUM-01",
        "atom_type": "CONCEPT",
        "description": "Euclid's Division Lemma: Given positive integers $a$ and $b$, there exist unique integers $q$ and $r$ such that $a = bq + r$ where $0 \\le r < b$."
      },
      {
        "atom_id": "ATOM-NUM-02",
        "atom_type": "PROCEDURE",
        "description": "Euclidean Algorithm for Greatest Common Divisor: $\\gcd(a, b) = \\gcd(b, a \\pmod b)$ repeatedly until the remainder is 0; the last non-zero remainder is $\\gcd(a, b)$."
      },
      {
        "atom_id": "ATOM-NUM-03",
        "atom_type": "RELATION",
        "description": "Bézout's Identity: For any integers $a$ and $b$, there exist integers $x, y \\in \\mathbb{Z}$ such that $ax + by = \\gcd(a, b)$. In particular, $\\gcd(a, b) = 1 \\iff \\exists x, y: ax + by = 1$."
      },
      {
        "atom_id": "ATOM-NUM-04",
        "atom_type": "INVARIANT",
        "description": "Two-Number Product Theorem: For any two positive integers $a$ and $b$, $\\gcd(a, b) \\times \\operatorname{lcm}(a, b) = a \\cdot b$. (Strictly restricted to pairs; does not generalize to triplets without inclusion-exclusion)."
      },
      {
        "atom_id": "ATOM-NUM-05",
        "atom_type": "STRATEGY",
        "description": "Proof by Contradiction for Irrationality: Assuming $\\sqrt{p} = \\frac{a}{b}$ where $\\gcd(a, b) = 1$, deriving that $p \\mid a^2 \\implies p \\mid a$, which implies $p \\mid b$, contradicting coprimality."
      }
    ],
    "misconceptions": [
      {
        "name": "Negative Remainder in Division",
        "flawed_action": "Calculating $-23 \\div 7$ as quotient $-3$ with remainder $-2$.",
        "diagnostic_cue": "Euclid's lemma requires $0 \\le r < b$. Write $-23 = 7(-4) + 5$. The quotient is $-4$ and the remainder is $+5$."
      },
      {
        "name": "Product Rule Applied to Three Numbers",
        "flawed_action": "Stating $\\operatorname{lcm}(a, b, c) = \\frac{abc}{\\gcd(a, b, c)}$.",
        "diagnostic_cue": "The product identity holds strictly for **two** numbers. For three numbers: $\\operatorname{lcm}(a, b, c) = \\frac{abc \\cdot \\gcd(a, b, c)}{\\gcd(a, b) \\gcd(b, c) \\gcd(c, a)}$."
      },
      {
        "name": "Assuming Coprimality Without Declaration",
        "flawed_action": "Proving $\\sqrt{2}$ is irrational by setting $\\sqrt{2} = a/b$ without explicitly asserting $\\gcd(a, b) = 1$.",
        "diagnostic_cue": "The contradiction depends entirely on the initial assumption that all common factors were cancelled. If $a/b$ were not coprime, finding a factor of 2 would not contradict the premise."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-NUM-01",
        "title": "Incomplete Euclidean Algorithm & Reverse Bézout Scaffold",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Find HCF(135, 225) using Euclid's Division Algorithm, and express it as 135x + 225y.\n\nStep 1: Apply Euclid's lemma to 225 and 135:\n        225 = 135 · [ ___ ] + [ ___ ]   ... (1)\nStep 2: Since remainder ≠ 0, apply lemma to 135 and remainder:\n        135 = [ ___ ] · [ ___ ] + [ ___ ]   ... (2)\nStep 3: Since remainder ≠ 0, apply lemma to [ ___ ] and [ ___ ]:\n        90 = [ ___ ] · [ ___ ] + 0      ... (3)\nStep 4: The last non-zero remainder is: HCF(135, 225) = [ ___ ]\n\nStep 5: Express HCF as linear combination (Bézout's identity):\n        From equation (2):  45 = 135 - 90 · [ ___ ]\n        From equation (1):  90 = 225 - 135 · [ ___ ]\n        Substitute (1) into (2):\n        45 = 135 - (225 - 135 · [ ___ ]) · 1\n        45 = 135 · [ ___ ] - 225 · [ ___ ]\n        x = [ ___ ],  y = [ ___ ]",
        "completion_key": "Step 1: 225 = 135 · 1 + 90\nStep 2: 135 = 90 · 1 + 45\nStep 3: 90 = 45 · 2 + 0\nStep 4: HCF = 45\nStep 5: 45 = 135 - 90·1; 90 = 225 - 135·1; 45 = 135·2 - 225·1 ==> x = 2, y = -1"
      },
      {
        "ttu_id": "TTU-NUM-02",
        "title": "Square Root Irrationality Dedekind-Contradiction Scaffold",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Prove that √3 is irrational.\n\nProof Structure: Proof by Contradiction.\nStep 1: Assume the contrary, that √3 is rational.\n        Then √3 = a / b, where a, b ∈ ℤ+, b ≠ 0, and gcd(a, b) = [ ___ ].\nStep 2: Squaring both sides:\n        3 = a² / b²  ==>  3b² = [ ___ ]   ... (1)\nStep 3: Since 3 divides 3b², 3 divides [ ___ ].\n        By prime divisibility theorem (if p|a² then p|a for prime p):\n        3 divides [ ___ ].\nStep 4: Since 3 divides a, we can write a = 3c for some integer c.\n        Substitute a = 3c into equation (1):\n        3b² = (3c)² = [ ___ ]c²\n        Dividing both sides by 3:  b² = [ ___ ]c²\nStep 5: This means 3 divides b², which implies 3 divides [ ___ ].\nStep 6: Deductive Contradiction:\n        From Step 3, 3 divides a. From Step 5, 3 divides b.\n        Therefore, a and b have at least [ ___ ] as a common factor.\n        This contradicts our initial assumption that gcd(a, b) = [ ___ ].\nConclusion: Our assumption was false. Therefore, √3 is [ RATIONAL / IRRATIONAL ].",
        "completion_key": "Step 1: gcd(a, b) = 1 (coprime)\nStep 2: a²\nStep 3: a²; a\nStep 4: 9c²; 3c²\nStep 5: b\nStep 6: 3; 1\nConclusion: IRRATIONAL (Hence Proved)."
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-NUM-01",
        "tier": "Foundation / CBSE",
        "description": "HCF and LCM via prime factorisation, terminating decimal form q = 2^m 5^n, irrationality proofs for √2, √5."
      },
      {
        "family_id": "FAMILY-NUM-02",
        "tier": "Olympiad / IOQM",
        "description": "Linear Diophantine equations ax + by = c, Chinese Remainder Theorem, Fermat's Little Theorem (a^{p-1} ≡ 1 mod p),\n  Legendre's formula for highest power of prime p dividing n!, and Wilson's theorem."
      },
      {
        "family_id": "FAMILY-NUM-03",
        "tier": "JEE Main",
        "description": "Divisibility in binomial expansions (1+x)^n, finding last two digits via mod 100, floor function properties."
      },
      {
        "family_id": "FAMILY-NUM-04",
        "tier": "JEE Advanced",
        "description": "Cyclotomic polynomial factorization, primitive roots, p-adic valuations in combinatorics,\n  and integer solutions to non-linear Diophantine equations (e.g. y² = x³ + k)."
      }
    ]
  },
  {
    "gate_id": "MATH-TRIG-RATIOS",
    "title": "Trigonometric Ratios & Pythagorean Identities",
    "section_number": 7,
    "domain": "Trigonometry & Identities",
    "grade_level": "Grade 10–11",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Tangent & Secant Domain Invariant**: $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$ and $\\sec\\theta = \\frac{1}{\\cos\\theta}$ require $\\cos\\theta \\neq 0 \\iff \\theta \\neq (2k+1)\\frac{\\pi}{2}$ for all $k \\in \\mathbb{Z}$.",
      "**Cotangent & Cosecant Domain Invariant**: $\\cot\\theta = \\frac{\\cos\\theta}{\\sin\\theta}$ and $\\csc\\theta = \\frac{1}{\\sin\\theta}$ require $\\sin\\theta \\neq 0 \\iff \\theta \\neq k\\pi$ for all $k \\in \\mathbb{Z}$.",
      "**Pythagorean Bounded Metric Invariant**: For all real angles $\\theta \\in \\mathbb{R}$, $\\sin^2\\theta + \\cos^2\\theta \\equiv 1$. Consequently, $|\\sin\\theta| \\le 1$ and $|\\cos\\theta| \\le 1$."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-TRIG-01",
        "atom_type": "CONCEPT",
        "description": "Trigonometric ratios as dimensionless scaling invariants of right-angled triangles under central dilation: $\\sin\\theta = \\frac{\\text{opp}}{\\text{hyp}}, \\cos\\theta = \\frac{\\text{adj}}{\\text{hyp}}, \\tan\\theta = \\frac{\\text{opp}}{\\text{adj}}$."
      },
      {
        "atom_id": "ATOM-TRIG-02",
        "atom_type": "INVARIANT",
        "description": "Fundamental Pythagorean identity trichotomy:\n  - $\\sin^2\\theta + \\cos^2\\theta = 1$\n  - $\\sec^2\\theta - \\tan^2\\theta = 1 \\iff (\\sec\\theta - \\tan\\theta)(\\sec\\theta + \\tan\\theta) = 1$\n  - $\\csc^2\\theta - \\cot^2\\theta = 1 \\iff (\\csc\\theta - \\cot\\theta)(\\csc\\theta + \\cot\\theta) = 1$"
      },
      {
        "atom_id": "ATOM-TRIG-03",
        "atom_type": "RELATION",
        "description": "Complementary angle co-function identities: $\\sin(90^\\circ - \\theta) = \\cos\\theta, \\cos(90^\\circ - \\theta) = \\sin\\theta, \\tan(90^\\circ - \\theta) = \\cot\\theta$."
      },
      {
        "atom_id": "ATOM-TRIG-04",
        "atom_type": "PROCEDURE",
        "description": "Reciprocal difference-of-squares reduction: Given $\\sec\\theta + \\tan\\theta = p$, immediately deduce $\\sec\\theta - \\tan\\theta = 1/p$, isolating $\\sec\\theta = \\frac{p+1/p}{2}$ and $\\tan\\theta = \\frac{p-1/p}{2}$."
      },
      {
        "atom_id": "ATOM-TRIG-05",
        "atom_type": "STRATEGY",
        "description": "Structural algebraic substitutions: converting rational trigonometric expressions into fundamental $(\\sin\\theta, \\cos\\theta)$ or utilizing $s = \\sin\\theta + \\cos\\theta, p = \\sin\\theta\\cos\\theta = \\frac{s^2-1}{2}$."
      }
    ],
    "misconceptions": [
      {
        "name": "Distributing Trigonometric Operators Over Addition",
        "flawed_action": "Writing $\\sin(A + B) = \\sin A + \\sin B$, or $\\sqrt{\\sin^2 A + \\cos^2 B} = \\sin A + \\cos B$.",
        "diagnostic_cue": "Trigonometric functions are non-linear transcendental mappings: $\\sin(A + B) = \\sin A \\cos B + \\cos A \\sin B \\neq \\sin A + \\sin B$."
      },
      {
        "name": "Unconditional Validity of Tangent Identities",
        "flawed_action": "Asserting $\\sec^2\\theta - \\tan^2\\theta = 1$ holds for all real $\\theta$.",
        "diagnostic_cue": "$\\sec\\theta$ and $\\tan\\theta$ are undefined at $\\theta = \\frac{\\pi}{2} + k\\pi$. The identity holds strictly on the domain of definition $\\theta \\neq (2k+1)\\frac{\\pi}{2}$."
      },
      {
        "name": "Unbounded Solutions for Sin and Cos",
        "flawed_action": "Accepting algebraic solutions $\\sin\\theta = 2$ or $\\cos\\theta = -1.5$ from quadratic factorizations.",
        "diagnostic_cue": "For all real $\\theta$, projections on the unit circle are bounded: $|\\sin\\theta| \\le 1$ and $|\\cos\\theta| \\le 1$. Values outside $[-1, 1]$ must be discarded."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-TRIG-01",
        "title": "Incomplete Reciprocal Conjugate Reduction Frame",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Given sec θ + tan θ = 5, find the exact values of sin θ, cos θ, and tan θ.\n\nStep 1: Write fundamental Pythagorean identity connecting sec θ and tan θ:\n        sec² θ - tan² θ = [ ___ ]\nStep 2: Factor as difference of squares:\n        (sec θ + tan θ)(sec θ - tan θ) = [ ___ ]\nStep 3: Substitute known value sec θ + tan θ = 5:\n        5 · (sec θ - tan θ) = 1  ==>  sec θ - tan θ = [ ___ ]   ... (1)\n        We also have:                 sec θ + tan θ = 5       ... (2)\n\nStep 4: Add equations (1) and (2):\n        2 sec θ = 5 + [ ___ ] = [ ___ ] / 5\n        sec θ = [ ___ ] / [ ___ ]\n        Therefore: cos θ = 1 / sec θ = [ ___ ] / [ ___ ]\n\nStep 5: Subtract equation (1) from equation (2):\n        2 tan θ = 5 - [ ___ ] = [ ___ ] / 5\n        tan θ = [ ___ ] / [ ___ ]\n\nStep 6: Compute sin θ:\n        sin θ = tan θ · cos θ = ([ ___ ] / [ ___ ]) · ([ ___ ] / [ ___ ]) = [ ___ ] / [ ___ ]",
        "completion_key": "Step 1: 1\nStep 2: 1\nStep 3: 1/5\nStep 4: 1/5; 26/5; 26/10 = 13/5; cos θ = 5/13\nStep 5: 1/5; 24/5; 24/10 = 12/5\nStep 6: (12/5) · (5/13) = 12/13"
      },
      {
        "ttu_id": "TTU-TRIG-02",
        "title": "Geometric Unit-Circle Angle Representation & Identity Verification Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-1.5, 1.5], y ∈ [-1.5, 1.5]",
        "scaffold": "Step 1: Ray intersects unit circle at point P with coordinates:\n        P = ([ ___ ], [ ___ ])\nStep 2: Right triangle OAP has base OA = cos θ, altitude AP = sin θ, hypotenuse OP = [ ___ ].\nStep 3: Divide Pythagorean equation (OA)² + (AP)² = (OP)² by (OA)² = cos² θ:\n        (cos² θ / cos² θ) + (sin² θ / [ ___ ]) = ([ ___ ] / cos² θ)\n        [ ___ ] + tan² θ = sec² θ\n\nStep 4: Domain validity condition:\n        Division by cos² θ requires cos θ ≠ [ ___ ]  ==>  θ ≠ [ ___ ]°",
        "completion_key": "Step 1: (cos θ, sin θ)\nStep 2: 1\nStep 3: cos² θ; 1; 1\nStep 4: 0; 90° (or π/2)"
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-TRIG-01",
        "tier": "Foundation / CBSE",
        "description": "Right-triangle ratio evaluations, standard angle evaluation tables, heights and distances (angles of elevation and depression)."
      },
      {
        "family_id": "FAMILY-TRIG-02",
        "tier": "Olympiad / IOQM",
        "description": "Non-trivial trigonometric equations, product telescoping cos(π/7)cos(2π/7)cos(4π/7) = -1/8, and Chebyshev polynomial representations."
      },
      {
        "family_id": "FAMILY-TRIG-03",
        "tier": "JEE Main",
        "description": "Compound and multiple angle expansions (sin 2θ, cos 2θ, tan 3θ), conditional identities in ΔABC (A+B+C=π), and maximum/minimum values of a cos θ + b sin θ + c."
      },
      {
        "family_id": "FAMILY-TRIG-04",
        "tier": "JEE Advanced",
        "description": "Inverse trigonometric relations with principal branch constraints, trigonometric series summation via C+iS method, and complex roots on the unit circle."
      }
    ]
  },
  {
    "gate_id": "MATH-ALG-POLYNOMIALS",
    "title": "Polynomial Rings, Factor Theorem & Newton Sums",
    "section_number": 8,
    "domain": "Algebra & Polynomial Rings",
    "grade_level": "Grade 9–10",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Non-Negative Integer Exponent Invariant**: A polynomial $P(x) = \\sum_{k=0}^n a_k x^k$ requires all exponents $k \\in \\mathbb{N}_0 = \\{0, 1, 2, \\dots\\}$. Expressions with fractional or negative exponents (e.g. $\\sqrt{x}, 1/x$) are non-polynomials.",
      "**Division Algorithm Degree Invariant**: For polynomials $P(x)$ and non-zero $D(x)$, there exist unique polynomials $Q(x)$ and $R(x)$ such that $P(x) = D(x)Q(x) + R(x)$ where either $R(x) \\equiv 0$ or $\\deg(R) < \\deg(D)$.",
      "**Factor Theorem Exact Equivalence**: A polynomial $P(x)$ has $(x - c)$ as a linear factor if and only if $P(c) = 0$."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-POLY-01",
        "atom_type": "CONCEPT",
        "description": "Polynomial as an element of ring $K[x]$, characterized by finite degree $\\deg(P) = n \\ge 0$ with leading coefficient $a_n \\neq 0$."
      },
      {
        "atom_id": "ATOM-POLY-02",
        "atom_type": "INVARIANT",
        "description": "Remainder Theorem: When $P(x)$ is divided by linear divisor $(x - c)$, the remainder is the scalar evaluation $R = P(c)$. If divided by $(ax - b)$, remainder is $P(b/a)$."
      },
      {
        "atom_id": "ATOM-POLY-03",
        "atom_type": "RELATION",
        "description": "Factor Theorem: $(x - c) \\mid P(x) \\iff P(c) = 0$. For integer polynomials, any rational root $p/q$ in lowest terms satisfies $p \\mid a_0$ and $q \\mid a_n$ (Rational Root Theorem)."
      },
      {
        "atom_id": "ATOM-POLY-04",
        "atom_type": "PROCEDURE",
        "description": "Synthetic division algorithm: Horner's method for rapid evaluation and quotient polynomial computation."
      },
      {
        "atom_id": "ATOM-POLY-05",
        "atom_type": "STRATEGY",
        "description": "Newton's Sum Recurrence: For polynomial $P(x) = a_n x^n + \\dots + a_0$ with roots $\\alpha_1, \\dots, \\alpha_n$, the power sums $S_k = \\sum_{i=1}^n \\alpha_i^k$ satisfy $a_n S_k + a_{n-1} S_{k-1} + \\dots = 0$."
      }
    ],
    "misconceptions": [
      {
        "name": "Remainder Degree Equal to or Greater Than Divisor",
        "flawed_action": "Dividing by quadratic divisor $(x^2 - 1)$ and assuming remainder is a constant $c$.",
        "diagnostic_cue": "When dividing by divisor of degree $m$, the remainder is a general polynomial of degree at most $m-1$. For quadratic divisor, remainder must be authored as $R(x) = Ax + B$."
      },
      {
        "name": "Treating Non-Polynomial Expressions as Polynomials",
        "flawed_action": "Stating $f(x) = x^2 + 2\\sqrt{x} + 1$ is a quadratic polynomial.",
        "diagnostic_cue": "Terms with non-integer exponents ($\\sqrt{x} = x^{1/2}$) violate the axiomatic definition of a polynomial ring $K[x]$."
      },
      {
        "name": "Sign Inversion in Divisor Evaluation",
        "flawed_action": "In finding remainder when $P(x)$ is divided by $(x + 2)$, calculating $P(2)$.",
        "diagnostic_cue": "Division by $(x - c)$ evaluates at $x = c$. For $(x + 2) = (x - (-2))$, the remainder is $P(-2)$."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-POLY-01",
        "title": "Incomplete Quadratic Remainder Reconstruction Frame",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: A polynomial P(x) leaves remainder 3 when divided by (x - 1), and remainder 7 when divided by (x - 3).\n      Find the remainder when P(x) is divided by (x - 1)(x - 3).\n\nStep 1: Identify degree of divisor: Divisor D(x) = (x - 1)(x - 3) has degree [ ___ ].\nStep 2: Express general remainder form: Since deg(D) = 2, remainder R(x) has form:\n        R(x) = [ ___ ]x + [ ___ ]\nStep 3: Write division algorithm equation:\n        P(x) = (x - 1)(x - 3) · Q(x) + (Ax + B)\n\nStep 4: Use Remainder Theorem conditions:\n        P(1) = 3  ==>  (0) · Q(1) + (A(1) + B) = 3  ==>   A + B = [ ___ ]   ... (1)\n        P(3) = 7  ==>  (0) · Q(3) + (A(3) + B) = 7  ==>  3A + B = [ ___ ]   ... (2)\n\nStep 5: Solve linear system for A and B:\n        Subtract (1) from (2):\n        (3A - A) + (B - B) = 7 - [ ___ ]\n        2A = [ ___ ]  ==>  A = [ ___ ]\n        Substitute A into (1):\n        [ ___ ] + B = 3  ==>  B = [ ___ ]\n\nConclusion: The remainder is R(x) = [ ___ ]x + [ ___ ].",
        "completion_key": "Step 1: 2\nStep 2: Ax + B\nStep 4: A + B = 3; 3A + B = 7\nStep 5: 3; 4; A = 2; 2 + B = 3 ==> B = 1\nConclusion: R(x) = 2x + 1"
      },
      {
        "ttu_id": "TTU-POLY-02",
        "title": "Newton Sum Power-Recurrence Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Let α and β be roots of x² - 5x + 3 = 0.\n      Let S_n = αⁿ + βⁿ. Find S_1, S_2, S_3, and derive S_n - 5·S_{n-1} + 3·S_{n-2} = 0.\n\nStep 1: Vieta's formulas:\n        α + β = [ ___ ],   α · β = [ ___ ]\nStep 2: Base values:\n        S_0 = α⁰ + β⁰ = 1 + 1 = [ ___ ]\n        S_1 = α + β = [ ___ ]\nStep 3: Newton sum recurrence for x² - 5x + 3 = 0:\n        Multiply α² - 5α + 3 = 0 by αⁿ⁻²:  αⁿ - 5αⁿ⁻¹ + 3αⁿ⁻² = 0\n        Multiply β² - 5β + 3 = 0 by βⁿ⁻²:  βⁿ - 5βⁿ⁻¹ + 3βⁿ⁻² = 0\n        Adding the two: S_n - 5·S_{n-1} + 3·S_{n-2} = [ ___ ]\n\nStep 4: Compute S_2:\n        S_2 - 5·S_1 + 3·S_0 = 0  ==>  S_2 = 5·([ ___ ]) - 3·([ ___ ]) = [ ___ ] - [ ___ ] = [ ___ ]\nStep 5: Compute S_3:\n        S_3 - 5·S_2 + 3·S_1 = 0  ==>  S_3 = 5·([ ___ ]) - 3·([ ___ ]) = [ ___ ] - [ ___ ] = [ ___ ]",
        "completion_key": "Step 1: α + β = 5, αβ = 3\nStep 2: S_0 = 2, S_1 = 5\nStep 3: 0 (Newton's recurrence: S_n = 5 S_{n-1} - 3 S_{n-2})\nStep 4: S_2 = 5(5) - 3(2) = 25 - 6 = 19\nStep 5: S_3 = 5(19) - 3(5) = 95 - 15 = 80"
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-POLY-01",
        "tier": "Foundation / CBSE",
        "description": "Zeros of linear and quadratic polynomials, factor theorem proofs, verification of relationship between zeros and coefficients."
      },
      {
        "family_id": "FAMILY-POLY-02",
        "tier": "Olympiad / IOQM",
        "description": "Integer-valued polynomials, Lagrange interpolation, Vieta's jumping on polynomial Diophantine equations, and Eisenstein's criterion for irreducibility."
      },
      {
        "family_id": "FAMILY-POLY-03",
        "tier": "JEE Main",
        "description": "Remainder with composite divisors (x-1)(x-2), common zeros between two polynomials, equations reducible to polynomials via reciprocal substitution x + 1/x = t."
      },
      {
        "family_id": "FAMILY-POLY-04",
        "tier": "JEE Advanced",
        "description": "Roots of unity polynomials sum_{k=0}^{n-1} x^k = 0, maximum number of real roots via Descartes' Rule of Signs, and Taylor expansion of polynomials about x = a."
      }
    ]
  },
  {
    "gate_id": "MATH-GEO-CIRCLES",
    "title": "Circle Theorems, Cyclic Quadrilaterals & Tangents",
    "section_number": 9,
    "domain": "Euclidean Geometry & Circles",
    "grade_level": "Grade 9–10",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Strict Radius Invariant**: A circle $\\mathcal{C}(O, r)$ requires radius $r > 0$. Points with $r = 0$ represent degenerate point-circles; $r < 0$ is undefined in Euclidean metric.",
      "**Non-Collinearity of Cyclic Vertices**: A cyclic quadrilateral $ABCD$ requires no three vertices to be collinear; vertices must lie in sequential cyclic order along the circumference.",
      "**Tangent Orthogonality Invariant**: At the point of contact $T$, the tangent line $l$ is strictly perpendicular to the radius $OT$: $l \\perp OT$.",
      "**Power of a Point Invariant**: For any point $P$ and circle $\\mathcal{C}(O, r)$, the power of $P$ is $\\operatorname{Pow}(P) = d^2 - r^2 = PA \\cdot PB$ for any secant line through $P$ intersecting the circle at $A$ and $B$. If $P$ is outside the circle and $PT$ is tangent, $PT^2 = PA \\cdot PB$."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-CIRC-01",
        "atom_type": "CONCEPT",
        "description": "Circle as locus of points equidistant from a fixed center. Chord, arc, subtended angle, and tangent defined under Euclidean metric."
      },
      {
        "atom_id": "ATOM-CIRC-02",
        "atom_type": "INVARIANT",
        "description": "Central-to-Inscribed Angle Theorem: The angle subtended by an arc at the center is double the angle subtended by it at any point on the remaining part of the circle: $\\angle AOB = 2 \\angle APB$."
      },
      {
        "atom_id": "ATOM-CIRC-03",
        "atom_type": "RELATION",
        "description": "Cyclic Quadrilateral Theorem: A quadrilateral is concyclic if and only if opposite angles are supplementary ($\\angle A + \\angle C = 180^\\circ$ and $\\angle B + \\angle D = 180^\\circ$), or exterior angle equals opposite interior angle. Ptolemy's Theorem: $AC \\cdot BD = AB \\cdot CD + BC \\cdot AD$."
      },
      {
        "atom_id": "ATOM-CIRC-04",
        "atom_type": "PROCEDURE",
        "description": "Alternate Segment Theorem: The angle between a tangent and a chord through the point of contact is equal to the angle subtended by the chord in the alternate segment."
      },
      {
        "atom_id": "ATOM-CIRC-05",
        "atom_type": "STRATEGY",
        "description": "Auxiliary radial and chord constructions:\n  - Joining the center $O$ to the point of contact of tangents to form congruent right-angled triangles ($\\triangle OPT_1 \\cong \\triangle OPT_2$ by RHS).\n  - Constructing common tangents or radical axes for intersecting or touching circles."
      }
    ],
    "misconceptions": [
      {
        "name": "Inscribed Angle Doubling on Opposite Arc",
        "flawed_action": "Concluding $\\angle AOB = 2\\angle APB$ when $P$ lies on the *minor* arc subtended by chord $AB$.",
        "diagnostic_cue": "The inscribed angle theorem strictly relates the subtended central angle to points on the *remaining* (opposite) arc. If $P$ is on the minor arc, $\\angle APB = 180^\\circ - \\frac{1}{2}\\angle AOB = \\frac{1}{2}\\operatorname{reflex}\\angle AOB$."
      },
      {
        "name": "Assuming Any Quadrilateral is Cyclic",
        "flawed_action": "Applying cyclic opposite angle relations ($\\angle B + \\angle D = 180^\\circ$) to general parallelograms or rhombuses.",
        "diagnostic_cue": "A quadrilateral is cyclic only if $\\angle A + \\angle C = 180^\\circ$. A parallelogram is cyclic if and only if it is a rectangle."
      },
      {
        "name": "Confusing Secant Segment Lengths",
        "flawed_action": "In the secant product $PA \\cdot PB$, calculating $PA \\cdot AB$.",
        "diagnostic_cue": "The Power of a Point identity strictly multiplies the distances from the external point $P$ to the two intersection points: $PA$ and $PB$, NOT the chord length $AB$."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-CIRC-01",
        "title": "Incomplete Alternate Segment Theorem Proof Scaffold",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Theorem: The angle between a tangent and a chord through the point of contact\n         is equal to the angle subtended by the chord in the alternate segment.\nGiven: Tangent XY touches circle at P. Chord PQ subtends ∠PRQ in the alternate segment.\nTo Prove: ∠QPY = ∠PRQ\n\nConstruction:\n  1. Draw diameter PM through center O.\n  2. Join MQ.\n\nProof Steps:\nStep 1: Since PM is a diameter, angle in semicircle is:\n        ∠PQM = [ ___ ]°\nStep 2: In right-angled ΔPQM:\n        ∠QPM + ∠PMQ = 180° - 90° = [ ___ ]°   ... (1)\nStep 3: Since PM ⊥ tangent XY at point of contact P:\n        ∠MPY = [ ___ ]°\nStep 4: Express ∠MPY as sum of adjacent angles:\n        ∠QPM + ∠QPY = [ ___ ]°               ... (2)\nStep 5: Equating (1) and (2):\n        ∠QPM + ∠PMQ = ∠QPM + ∠QPY  ==>  ∠QPY = ∠[ ___ ]\nStep 6: Circle Invariant:\n        ∠PMQ and ∠PRQ are subtended by the same chord [ ___ ] in the same segment.\n        Therefore: ∠PMQ = ∠[ ___ ]\nConclusion: ∠QPY = ∠PRQ  (Hence Proved)",
        "completion_key": "Step 1: 90°\nStep 2: 90°\nStep 3: 90°\nStep 4: 90°\nStep 5: PMQ\nStep 6: Same chord PQ; PRQ\nConclusion: ∠QPY = ∠PRQ"
      },
      {
        "ttu_id": "TTU-CIRC-02",
        "title": "Power of a Point & Tangent Length Geometric Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-4, 6], y ∈ [-4, 4]",
        "scaffold": "Step 1: Distance from P to center O: OP = [ ___ ].\nStep 2: In right ΔOPT (since OT ⊥ PT):\n        PT² = OP² - OT² = [ ___ ]² - [ ___ ]² = [ ___ ] - [ ___ ] = [ ___ ]\n        Length of tangent PT = √[ ___ ] = [ ___ ].\n\nStep 3: Secant PAB passes through center O:\n        Intersection points along line OP:\n        Near intersection A has distance: PA = OP - r = 5 - [ ___ ] = [ ___ ]\n        Far intersection B has distance:  PB = OP + r = 5 + [ ___ ] = [ ___ ]\n\nStep 4: Verify Power of a Point identity:\n        PA · PB = [ ___ ] · [ ___ ] = [ ___ ]\n        Does PT² = PA · PB? [ YES / NO ]",
        "completion_key": "Step 1: 5\nStep 2: 5² - 3² = 25 - 9 = 16; PT = √16 = 4\nStep 3: 5 - 3 = 2; 5 + 3 = 8\nStep 4: 2 · 8 = 16. PT² (16) = PA · PB (16) ==> YES."
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-CIRC-01",
        "tier": "Foundation / CBSE",
        "description": "Tangent perpendicularity proofs, lengths of tangents from external point, cyclic quadrilateral angle deductions, and angle in semicircle."
      },
      {
        "family_id": "FAMILY-CIRC-02",
        "tier": "Olympiad / IOQM",
        "description": "Ptolemy's Theorem, Simson line, Miquel's theorem, radical axis of coaxal circles, and spiral homothety."
      },
      {
        "family_id": "FAMILY-CIRC-03",
        "tier": "JEE Main",
        "description": "Tangents and normals in Cartesian form xx₁ + yy₁ = r², condition of tangency c² = a²(1+m²), chord of contact T = 0, length of chord 2√(r²-d²)."
      },
      {
        "family_id": "FAMILY-CIRC-04",
        "tier": "JEE Advanced",
        "description": "Family of circles S + λL = 0 and S + λS' = 0, common chord, director circle, and orthogonal intersection condition 2g₁g₂ + 2f₁f₂ = c₁ + c₂."
      }
    ]
  },
  {
    "gate_id": "MATH-SEQ-AP",
    "title": "Arithmetic Progressions & Series Summations",
    "section_number": 10,
    "domain": "Sequences & Series",
    "grade_level": "Grade 10–11",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Strict Discrete Index Invariant**: The term index $n$ must belong to the positive integers: $n \\in \\mathbb{Z}^+ = \\{1, 2, 3, \\dots\\}$. Fractional or negative term indices (e.g. $a_{3.5}$ or $a_{-2}$) are undefined in standard progression theory.",
      "**Common Difference Invariant**: A sequence $(a_n)$ is an AP if and only if $a_{n+1} - a_n = d$ is a constant independent of $n$ for all $n \\ge 1$.",
      "**Non-Degenerate AP Condition**: If $d = 0$, the progression is a constant sequence ($a, a, a, \\dots$). If $d \\neq 0$, the sequence is strictly monotonic."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-AP-01",
        "atom_type": "CONCEPT",
        "description": "Arithmetic Progression as a linear discrete function $f(n) = a + (n-1)d = dn + (a-d)$ over domain $\\mathbb{Z}^+$. The common difference $d$ corresponds to the discrete slope."
      },
      {
        "atom_id": "ATOM-AP-02",
        "atom_type": "INVARIANT",
        "description": "General Term Formula: $a_n = a + (n-1)d$. Term from the end: $a_n' = l - (n-1)d$ where $l$ is the last term."
      },
      {
        "atom_id": "ATOM-AP-03",
        "atom_type": "PROCEDURE",
        "description": "Gauss Summation Identity: $S_n = \\frac{n}{2}[2a + (n-1)d] = \\frac{n}{2}(a + l)$. Symmetric pairing: $a_k + a_{n-k+1} = a_1 + a_n$ for all $1 \\le k \\le n$."
      },
      {
        "atom_id": "ATOM-AP-04",
        "atom_type": "RELATION",
        "description": "Term-Sum Inversion: $a_n = S_n - S_{n-1}$ for $n \\ge 2$, with $a_1 = S_1$. If $S_n = An^2 + Bn$, the sequence is an AP with common difference $d = 2A$ and first term $a = A + B$."
      },
      {
        "atom_id": "ATOM-AP-05",
        "atom_type": "STRATEGY",
        "description": "Symmetric Variable Selection for Word Problems:\n  - 3 terms in AP: $(a - d), a, (a + d)$ with sum $= 3a$.\n  - 4 terms in AP: $(a - 3d), (a - d), (a + d), (a + 3d)$ with common difference $2d$ and sum $= 4a$.\n  - 5 terms in AP: $(a - 2d), (a - d), a, (a + d), (a + 2d)$ with sum $= 5a$."
      }
    ],
    "misconceptions": [
      {
        "name": "Off-by-One in Term Index",
        "flawed_action": "Writing $a_n = a + nd$.",
        "diagnostic_cue": "For the first term ($n = 1$), the difference $d$ has not been added yet ($a_1 = a + (1-1)d = a$). Adding $nd$ shifts every term forward by one position ($a + nd = a_{n+1}$)."
      },
      {
        "name": "Quadratic Term vs Quadratic Sum Confusion",
        "flawed_action": "Concluding $a_n = 3n^2 + 2n$ is an AP because it contains $n$.",
        "diagnostic_cue": "An AP has a *linear* general term $a_n = dn + c$. A *quadratic* polynomial in $n$ describes the *sum* $S_n = An^2 + Bn$, NOT the individual term $a_n$."
      },
      {
        "name": "Double Counting in Difference for Even Term Selections",
        "flawed_action": "Choosing 4 terms as $(a - 3d), (a - d), (a + d), (a + 3d)$ and setting common difference equal to $d$.",
        "diagnostic_cue": "The step size between $(a - d)$ and $(a + d)$ is $(a + d) - (a - d) = 2d$. Therefore, the common difference is $2d$, NOT $d$."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-AP-01",
        "title": "Incomplete Gaussian Pair-Summation Derivation Frame",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Derive the sum formula Sn = n/2 · [2a + (n-1)d] using Gauss's reverse summation method.\n\nStep 1: Write sum in ascending order:\n        Sn = a + (a + d) + (a + 2d) + ... + [l - d] + l       ... (1)\nStep 2: Write sum in reversed descending order:\n        Sn = l + (l - d) + [ _____ ] + ... + (a + d) + a       ... (2)\nStep 3: Add equations (1) and (2) term-by-term:\n        Sn + Sn = (a + l) + [(a + d) + (l - d)] + ... + (l + a)\n        2Sn = (a + l) + (a + [ ___ ]) + ... + (a + l)\n\nStep 4: Count number of identical paired terms:\n        There are [ ___ ] terms, each equal to (a + l).\n        2Sn = [ ___ ] · (a + l)  ==>  Sn = ([ ___ ] / 2) · (a + l)\n\nStep 5: Substitute the last term formula l = a + ([ ___ ] - 1)d:\n        Sn = (n / 2) · [a + (a + (n - 1)d)]\n        Sn = (n / 2) · [ [ ___ ]a + (n - 1)d ]   (Hence Derived)",
        "completion_key": "Step 2: (l - 2d)\nStep 3: l\nStep 4: n terms; n · (a + l); (n / 2)\nStep 5: n; 2a"
      },
      {
        "ttu_id": "TTU-AP-02",
        "title": "Quadratic Sum-to-Term Decompilation Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Given the sum of first n terms of a sequence is Sn = 3n² + 5n.\n      Prove that it is an AP, and find the first term a and common difference d.\n\nStep 1: Find the first term a:\n        a = a₁ = S₁ = 3(1)² + 5(1) = 3 + 5 = [ ___ ]\n\nStep 2: Find the sum of first two terms S₂:\n        S₂ = 3(2)² + 5(2) = 3(4) + 10 = [ ___ ] + 10 = [ ___ ]\n\nStep 3: Find the second term a₂:\n        a₂ = S₂ - S₁ = [ ___ ] - [ ___ ] = [ ___ ]\n\nStep 4: Calculate the candidate common difference d:\n        d = a₂ - a₁ = [ ___ ] - [ ___ ] = [ ___ ]\n\nStep 5: General proof using Sn - S_{n-1}:\n        an = Sn - S_{n-1}\n           = (3n² + 5n) - [ 3(n - 1)² + 5(n - 1) ]\n           = (3n² + 5n) - [ 3(n² - 2n + 1) + 5n - 5 ]\n           = (3n² + 5n) - [ 3n² - 6n + 3 + 5n - 5 ]\n           = (3n² + 5n) - [ 3n² - n - 2 ]\n           = [ ___ ]n + [ ___ ]\n\nStep 6: Since an is a linear polynomial in n, the sequence is an AP:\n        Common difference = coefficient of n = [ ___ ]\n        First term = a₁ = 6(1) + 2 = [ ___ ]",
        "completion_key": "Step 1: 8\nStep 2: 12; 22\nStep 3: 22 - 8 = 14\nStep 4: 14 - 8 = 6\nStep 5: 6n + 2\nStep 6: 6; 8"
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-AP-01",
        "tier": "Foundation / CBSE",
        "description": "Finding n-th term, sum of n terms, checking if a number belongs to an AP (n ∈ ℤ+), savings/installment word problems."
      },
      {
        "family_id": "FAMILY-AP-02",
        "tier": "Olympiad / IOQM",
        "description": "APs with integer constraints, Green-Tao theorem context (primes in AP), partitioning sets into APs, and nonlinear Diophantine systems with AP terms."
      },
      {
        "family_id": "FAMILY-AP-03",
        "tier": "JEE Main",
        "description": "Ratio of sums of two APs S_n / S_n' = (7n+1)/(4n+27) mapping to ratio of m-th terms by substitution n = 2m - 1, arithmetic-geometric progressions sum n rⁿ."
      },
      {
        "family_id": "FAMILY-AP-04",
        "tier": "JEE Advanced",
        "description": "Telescoping series involving reciprocals of AP products sum 1/(a_k a_{k+1}), AP properties in logarithms (log a, log b, log c in AP <=> a, b, c in GP), and multidimensional grid lattices."
      }
    ]
  },
  {
    "gate_id": "MATH-GEO-COORDINATES",
    "title": "Cartesian Coordinate Geometry & Planar Invariants",
    "section_number": 11,
    "domain": "Cartesian Coordinate Geometry",
    "grade_level": "Grade 9–10",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Cartesian Metric Invariant**: The Euclidean distance between $P_1(x_1, y_1)$ and $P_2(x_2, y_2)$ is $d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2} \\ge 0$. Distance is zero if and only if $P_1 \\equiv P_2$.",
      "**Section Formula Denominator Constraint**: The section ratio $m : n$ must satisfy $m + n \\neq 0$ for internal division ($m, n > 0$) and external division ($m/n \\neq -1$).",
      "**Non-Degenerate Area Invariant**: Three points $A, B, C$ form a triangle if and only if the shoelace determinant is non-zero: $\\Delta = \\frac{1}{2} |x_1(y_2 - y_3) + x_2(y_3 - y_1) + x_3(y_1 - y_2)| > 0$. If $\\Delta = 0$, the points are strictly collinear."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-COORD-01",
        "atom_type": "CONCEPT",
        "description": "Cartesian coordinates as an isometric bijection between Euclidean plane $\\mathbb{E}^2$ and $\\mathbb{R}^2$. Abscissa $x$ as signed orthogonal distance from $y$-axis; ordinate $y$ as signed orthogonal distance from $x$-axis."
      },
      {
        "atom_id": "ATOM-COORD-02",
        "atom_type": "INVARIANT",
        "description": "Distance Formula as Pythagorean projection: $d^2 = (\\Delta x)^2 + (\\Delta y)^2$."
      },
      {
        "atom_id": "ATOM-COORD-03",
        "atom_type": "PROCEDURE",
        "description": "Section Formula: Coordinates of point $P$ dividing segment $AB$ in ratio $m : n$:\n  - Internal division: $P\\left(\\frac{m x_2 + n x_1}{m + n}, \\frac{m y_2 + n y_1}{m + n}\\right)$.\n  - Centroid of triangle $\\triangle ABC$: $G\\left(\\frac{x_1 + x_2 + x_3}{3}, \\frac{y_1 + y_2 + y_3}{3}\\right)$, dividing each median in ratio $2 : 1$."
      },
      {
        "atom_id": "ATOM-COORD-04",
        "atom_type": "RELATION",
        "description": "Shoelace Area Formula: $\\operatorname{Area}(\\triangle ABC) = \\frac{1}{2} |x_1 y_2 + x_2 y_3 + x_3 y_1 - (x_2 y_1 + x_3 y_2 + x_1 y_3)| = \\frac{1}{2} \\left| \\det \\begin{pmatrix} x_1 & y_1 & 1 \\\\ x_2 & y_2 & 1 \\\\ x_3 & y_3 & 1 \\end{pmatrix} \\right|$."
      },
      {
        "atom_id": "ATOM-COORD-05",
        "atom_type": "STRATEGY",
        "description": "Collinearity & Ratio Discovery: Using ratio $k : 1$ to determine unknown division ratios and verifying $k > 0$ (internal) vs $k < 0$ (external)."
      }
    ],
    "misconceptions": [
      {
        "name": "Inverting Point Order in Section Formula",
        "flawed_action": "In dividing segment from $A$ to $B$ in ratio $m : n$, writing $\\frac{m x_1 + n x_2}{m + n}$.",
        "diagnostic_cue": "The ratio multiplier cross-multiplies to the *opposite* point: ratio $m$ attached to $A$ multiplies $B$'s coordinates ($x_2$), and ratio $n$ attached to $B$ multiplies $A$'s coordinates ($x_1$): $x = \\frac{m x_2 + n x_1}{m + n}$."
      },
      {
        "name": "Omitting Absolute Value in Area Calculation",
        "flawed_action": "Calculating the determinant as $-15$ and reporting area as $-7.5$.",
        "diagnostic_cue": "Geometric area is strictly non-negative. The determinant computes signed area depending on clockwise vs counterclockwise orientation. The physical area requires the absolute value: $\\text{Area} = \\frac{1}{2}|-15| = 7.5$."
      },
      {
        "name": "External Division Denominator Sign Error",
        "flawed_action": "Writing external division coordinates as $\\frac{m x_2 + n x_1}{m - n}$.",
        "diagnostic_cue": "For external division in ratio $m:n$, treat ratio as $m : (-n)$. The formula is $x = \\frac{m x_2 - n x_1}{m - n}$. Both numerator and denominator must carry the minus sign."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-COORD-01",
        "title": "Incomplete Section Formula Ratio Discovery Frame",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: In what ratio does the point P(2, -5) divide the line segment joining\n      A(-3, 5) and B(4, -9)?\n\nStep 1: Assume point P divides segment AB in the ratio k : 1.\n        Coordinates of A: (x₁, y₁) = (-3, 5)\n        Coordinates of B: (x₂, y₂) = (4, -9)\n\nStep 2: Apply section formula for x-coordinate:\n        x_P = (k · x₂ + 1 · x₁) / (k + 1)\n        2   = (k · [ ___ ] + 1 · [ ___ ]) / (k + 1)\n        2   = ([ ___ ]k - [ ___ ]) / (k + 1)\n\nStep 3: Cross multiply and solve for k:\n        2(k + 1) = 4k - 3\n        2k + 2   = 4k - 3\n        2k       = [ ___ ]  ==>  k = [ ___ ] / [ ___ ]\n\nStep 4: Verify with y-coordinate:\n        y_P = (k · y₂ + 1 · y₁) / (k + 1)\n            = ((5/2) · (-9) + 5) / ((5/2) + 1)\n            = (-45/2 + 10/2) / (7/2)\n            = (-35/2) / (7/2) = -35 / 7 = [ ___ ]\n        Does this match y_P = -5? [ YES / NO ]\n\nConclusion: The segment is divided in the ratio [ ___ ] : [ ___ ] internally.",
        "completion_key": "Step 2: 4; -3; 4; 3\nStep 3: 5; 5 / 2\nStep 4: -5; YES\nConclusion: 5 : 2"
      },
      {
        "ttu_id": "TTU-COORD-02",
        "title": "Shoelace Determinant Planar Area Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-2, 6], y ∈ [-2, 8]",
        "scaffold": "Step 1: Write Shoelace Formula layout:\n        Δ = 1/2 | x₁(y₂ - y₃) + x₂(y₃ - y₁) + x₃(y₁ - y₂) |\n\nStep 2: Substitute coordinates:\n        Δ = 1/2 | 1·(6 - 8) + 4·(8 - 2) + 3·(2 - 6) |\n        Δ = 1/2 | 1·([ ___ ]) + 4·([ ___ ]) + 3·([ ___ ]) |\n        Δ = 1/2 | [ ___ ] + [ ___ ] + [ ___ ] |\n        Δ = 1/2 | [ ___ ] |\n\nStep 3: Compute final area:\n        Area(ΔABC) = 1/2 · [ ___ ] = [ ___ ] sq units.\n\nStep 4: Collinearity check:\n        Since Area ≠ 0, are the points A, B, C collinear? [ YES / NO ]",
        "completion_key": "Step 2: -2; 6; -4; -2; 24; -12; 10\nStep 3: 10; 5\nStep 4: NO (non-collinear)."
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-COORD-01",
        "tier": "Foundation / CBSE",
        "description": "Distance between points, finding coordinates of equidistant points on axes, section formula internal division, finding ratios, collinearity proofs."
      },
      {
        "family_id": "FAMILY-COORD-02",
        "tier": "Olympiad / IOQM",
        "description": "Pick's Theorem (A = I + B/2 - 1) for lattice polygons, area coordinates (barycentric coordinates), and collinearity via Menelaus in coordinates."
      },
      {
        "family_id": "FAMILY-COORD-03",
        "tier": "JEE Main",
        "description": "Locus problems, shift of origin (X = x-h, Y = y-k), condition for lines to form equilateral triangle, distance between parallel lines."
      },
      {
        "family_id": "FAMILY-COORD-04",
        "tier": "JEE Advanced",
        "description": "Concurrence of lines via 3x3 determinant, rotation of axes through angle θ, reflection of point across arbitrary line ax+by+c=0, and harmonic conjugates."
      }
    ]
  },
  {
    "gate_id": "MATH-CONIC-PARABOLA",
    "title": "Conic Sections & Parabolic Geometry",
    "section_number": 12,
    "domain": "Conic Sections & Analytical Geometry",
    "grade_level": "Grade 11–12",
    "exam_families": [
      "CBSE",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Strict Eccentricity Invariant**: A conic section is a parabola if and only if eccentricity $e = \\frac{SP}{PM} \\equiv 1$ strictly, where $S$ is the focus and $PM$ is the perpendicular distance from point $P$ to the directrix line $L$.",
      "**Non-Incident Focus Precondition**: The focus $S$ must not lie on the directrix line $L$. If $S \\in L$, the locus degenerates into a single straight line through $S$ perpendicular to $L$.",
      "**Focal Parameter Invariant**: The focal length $a > 0$ strictly. The distance between focus and directrix is $2a$. Latus rectum length is $4a$."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-PARAB-01",
        "atom_type": "CONCEPT",
        "description": "Parabola as the geometric locus of a point moving such that its distance from a fixed point (focus $S$) equals its perpendicular distance from a fixed straight line (directrix $L$)."
      },
      {
        "atom_id": "ATOM-PARAB-02",
        "atom_type": "INVARIANT",
        "description": "Standard Four-Form Canonical Coordinates:\n  - $y^2 = 4ax$: Opens right, focus $(a, 0)$, directrix $x = -a$, vertex $(0, 0)$.\n  - $y^2 = -4ax$: Opens left, focus $(-a, 0)$, directrix $x = a$.\n  - $x^2 = 4ay$: Opens up, focus $(0, a)$, directrix $y = -a$.\n  - $x^2 = -4ay$: Opens down, focus $(0, -a)$, directrix $y = a$."
      },
      {
        "atom_id": "ATOM-PARAB-03",
        "atom_type": "RELATION",
        "description": "Parametric representation: Point $P(t) = (at^2, 2at)$. Tangent line at $t$: $ty = x + at^2$. Focal chord endpoint parameter invariant: If $t_1, t_2$ are endpoints of a focal chord, then $t_1 t_2 = -1$."
      },
      {
        "atom_id": "ATOM-PARAB-04",
        "atom_type": "PROCEDURE",
        "description": "Tangency Condition: A line $y = mx + c$ touches the parabola $y^2 = 4ax$ if and only if $c = \\frac{a}{m}$ (for $m \\neq 0$). The point of contact is $\\left(\\frac{a}{m^2}, \\frac{2a}{m}\\right)$."
      },
      {
        "atom_id": "ATOM-PARAB-05",
        "atom_type": "STRATEGY",
        "description": "Optical Reflection Invariant: Any ray parallel to the principal axis of symmetry reflects off the parabolic mirror directly through the focus $S$."
      }
    ],
    "misconceptions": [
      {
        "name": "Inverting Axis Orientation in Standard Forms",
        "flawed_action": "Writing focus of $x^2 = 8y$ as $(2, 0)$.",
        "diagnostic_cue": "In $x^2 = 4ay$, the axis of symmetry is vertical ($y$-axis). The focus lies on the $y$-axis at $(0, a) = (0, 2)$, NOT on the $x$-axis."
      },
      {
        "name": "Applying $c = a/m$ to Vertical Parabolas",
        "flawed_action": "Stating line $y = mx + c$ touches $x^2 = 4ay$ when $c = a/m$.",
        "diagnostic_cue": "The condition $c = a/m$ holds strictly for horizontal parabola $y^2 = 4ax$. For vertical parabola $x^2 = 4ay$, the tangency condition is $c = -am^2$."
      },
      {
        "name": "Latus Rectum as Arbitrary Focal Segment",
        "flawed_action": "Measuring the length of an inclined focal chord as $4a$.",
        "diagnostic_cue": "The latus rectum is specifically the focal chord *perpendicular* to the axis of symmetry. Any inclined focal chord has length $a(t + 1/t)^2 \\ge 4a$."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-PARAB-01",
        "title": "Incomplete Focus-Directrix Standard Form Derivation Frame",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Derive the standard equation of parabola y² = 4ax using focus S(a, 0) and directrix x = -a.\n\nStep 1: Let P(x, y) be any point on the parabola.\n        Distance to focus S(a, 0):\n        SP = √[ (x - [ ___ ])² + (y - [ ___ ])² ]\n\nStep 2: Distance to directrix line x + a = 0:\n        PM = | x + [ ___ ] | / √[ 1² + 0² ] = | x + [ ___ ] |\n\nStep 3: Equating SP = PM by definition of parabola (eccentricity e = 1):\n        √[ (x - a)² + y² ] = | x + a |\n\nStep 4: Squaring both sides:\n        (x - a)² + y² = (x + a)²\n        [ x² - [ ___ ]ax + a² ] + y² = [ x² + [ ___ ]ax + a² ]\n\nStep 5: Cancel common terms x² and a² from both sides:\n        -2ax + y² = 2ax\n        y² = 2ax + [ ___ ]ax\n        y² = [ ___ ]ax   (Hence Derived)",
        "completion_key": "Step 1: a; 0\nStep 2: a; a\nStep 4: 2; 2\nStep 5: 2; 4"
      },
      {
        "ttu_id": "TTU-PARAB-02",
        "title": "Focal Chord Harmonic Mean Geometric Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-3, 8], y ∈ [-6, 6]",
        "scaffold": "Step 1: Endpoint P coordinates: P(t) = (at², 2at) = (1·2², 2·1·2) = ([ ___ ], [ ___ ]).\nStep 2: Focal chord parameter property:\n        t₁ · t₂ = [ ___ ]  ==>  2 · t₂ = -1  ==>  t₂ = [ ___ ] / [ ___ ]\n\nStep 3: Endpoint Q coordinates:\n        x_Q = a · t₂² = 1 · (-1/2)² = [ ___ ] / [ ___ ]\n        y_Q = 2a · t₂ = 2(1)(-1/2) = [ ___ ]\n        Q = ([ ___ ], [ ___ ])\n\nStep 4: Length of focal chord formula:\n        Length PQ = a(t + 1/t)² = 1 · (2 - [ ___ ])² = ( [ ___ ] / 2 )² = [ ___ ] / [ ___ ]",
        "completion_key": "Step 1: (4, 4)\nStep 2: -1; -1 / 2\nStep 3: 1 / 4; -1; (1/4, -1)\nStep 4: 1/2; 5; 25 / 4 (6.25)"
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-PARAB-01",
        "tier": "Foundation / CBSE",
        "description": "Vertex, focus, axis, directrix equation, and latus rectum length extraction for standard parabolas."
      },
      {
        "family_id": "FAMILY-PARAB-02",
        "tier": "Olympiad / IOQM",
        "description": "Archimedean quadrature of parabola segment (area = 4/3 of inscribed triangle), Poncelet's porism, and focal inequalities."
      },
      {
        "family_id": "FAMILY-PARAB-03",
        "tier": "JEE Main",
        "description": "Tangent and normal equations (y = mx - 2am - am³), point of intersection of perpendicular tangents on directrix, common tangents to parabola and circle."
      },
      {
        "family_id": "FAMILY-PARAB-04",
        "tier": "JEE Advanced",
        "description": "Co-normal points (sum of slopes = 0), circle through feet of three co-normals passing through vertex, and locus of centroids of normal triangles."
      }
    ]
  },
  {
    "gate_id": "MATH-CALC-LIMITS",
    "title": "Calculus Foundations, Limits & Indeterminate Forms",
    "section_number": 13,
    "domain": "Calculus Foundations & Real Analysis",
    "grade_level": "Grade 11–12",
    "exam_families": [
      "CBSE",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Deleted Punctured Neighborhood Precondition**: The limit $\\lim_{x \\to a} f(x)$ evaluates behavior in a punctured neighborhood $0 < |x - a| < \\delta$. The value $f(a)$ at the exact point is entirely irrelevant to the existence or value of the limit.",
      "**Left-Right Hand Limit Equality Invariant**: $\\lim_{x \\to a} f(x) = L \\iff \\lim_{x \\to a^-} f(x) = \\lim_{x \\to a^+} f(x) = L$ where $L \\in \\mathbb{R}$ is finite.",
      "**Radian Measure Precondition in Trigonometric Limits**: The fundamental trigonometric limit $\\lim_{\\theta \\to 0} \\frac{\\sin\\theta}{\\theta} = 1$ is valid if and only if $\\theta$ is measured in **radians**. If $\\theta$ is in degrees, the limit is $\\frac{\\pi}{180}$."
    ],
    "atoms": [
      {
        "atom_id": "ATOM-LIM-01",
        "atom_type": "CONCEPT",
        "description": "Limit as local convergence: For every $\\varepsilon > 0$ there exists $\\delta > 0$ such that $0 < |x - a| < \\delta \\implies |f(x) - L| < \\varepsilon$."
      },
      {
        "atom_id": "ATOM-LIM-02",
        "atom_type": "INVARIANT",
        "description": "Fundamental Algebraic Standard Limit: $\\lim_{x \\to a} \\frac{x^n - a^n}{x - a} = n a^{n-1}$ for all $n \\in \\mathbb{Q}$ ($a > 0$)."
      },
      {
        "atom_id": "ATOM-LIM-03",
        "atom_type": "RELATION",
        "description": "Sandwich / Squeeze Theorem: If $g(x) \\le f(x) \\le h(x)$ in a punctured neighborhood of $a$, and $\\lim_{x \\to a} g(x) = \\lim_{x \\to a} h(x) = L$, then $\\lim_{x \\to a} f(x) = L$."
      },
      {
        "atom_id": "ATOM-LIM-04",
        "atom_type": "PROCEDURE",
        "description": "Resolution of Indeterminate Form $1^\\infty$: $\\lim_{x \\to a} [f(x)]^{g(x)} = e^{\\lim_{x \\to a} [f(x) - 1] \\cdot g(x)}$ where $\\lim f(x) = 1$ and $\\lim g(x) = \\infty$."
      },
      {
        "atom_id": "ATOM-LIM-05",
        "atom_type": "STRATEGY",
        "description": "Taylor / Maclaurin series expansion dominance: replacing $\\sin x = x - \\frac{x^3}{6} + \\mathcal{O}(x^5)$, $e^x = 1 + x + \\frac{x^2}{2} + \\mathcal{O}(x^3)$, $\\ln(1+x) = x - \\frac{x^2}{2} + \\mathcal{O}(x^3)$ to rapidly cancel vanishing lower-order differentials."
      }
    ],
    "misconceptions": [
      {
        "name": "Evaluating $f(a)$ Instead of Limit",
        "flawed_action": "Stating $\\lim_{x \\to 0} \\frac{\\sin x}{x}$ is undefined because $\\frac{\\sin 0}{0} = \\frac{0}{0}$.",
        "diagnostic_cue": "A limit evaluates the approach in a punctured neighborhood $x \\neq 0$. Cancellation of vanishing factors is mathematically rigorous because $x \\neq 0$."
      },
      {
        "name": "Treating $1^\\infty$ as Trivial 1",
        "flawed_action": "Concluding $\\lim_{x \\to 0} (1 + x)^{1/x} = 1$ because \"1 to any power is 1\".",
        "diagnostic_cue": "The base $(1+x)$ is not identical to constant 1; it is a dynamic quantity approaching 1 at a rate competing with the exponent approaching $\\infty$. This tension resolves to Euler's number $e$."
      },
      {
        "name": "Degree Angle in Trigonometric Limits",
        "flawed_action": "Computing $\\lim_{x \\to 0} \\frac{\\sin x^\\circ}{x} = 1$.",
        "diagnostic_cue": "The derivative and limit proofs rely on arc length on the unit circle equaling radian angle $\\theta$. In degrees, $x^\\circ = \\frac{\\pi x}{180}$ radians, so the limit is $\\frac{\\pi}{180}$."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-LIM-01",
        "title": "Incomplete Rationalization & Algebraic Factorization Scaffold",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Evaluate lim_{x -> 0} [ √(1 + x) - √(1 - x) ] / x.\n\nStep 1: Check form at x = 0:\n        Numerator: √(1 + 0) - √(1 - 0) = 1 - 1 = [ ___ ]\n        Denominator: [ ___ ]\n        Form is: [ 0/0 / ∞/∞ / 1^∞ ]\n\nStep 2: Multiply numerator and denominator by conjugate:\n        Conjugate of [ √(1+x) - √(1-x) ] is [ √(1+x) + √(1-x) ]\n        Expression = [ (√(1+x) - √(1-x))(√(1+x) + √(1-x)) ] / [ x · (√(1+x) + √(1-x)) ]\n\nStep 3: Simplify numerator using (a - b)(a + b) = a² - b²:\n        Numerator = (1 + x) - (1 - x) = 1 + x - 1 + x = [ ___ ]x\n\nStep 4: Cancel common non-zero factor x (since x -> 0 implies x ≠ 0):\n        Expression = [ ___ ] / [ √(1+x) + √(1-x) ]\n\nStep 5: Evaluate limit by direct substitution:\n        Limit = [ ___ ] / [ √(1+0) + √(1-0) ] = [ ___ ] / (1 + 1) = [ ___ ] / 2 = [ ___ ]",
        "completion_key": "Step 1: 0; 0; 0/0\nStep 3: 2\nStep 4: 2\nStep 5: 2; 2; 2; 1"
      },
      {
        "ttu_id": "TTU-LIM-02",
        "title": "Indeterminate Form $1^\\infty$ Exponential Decompilation Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Evaluate L = lim_{x -> 0} (cos x)^{1/x²}.\n\nStep 1: Check form at x = 0:\n        Base: cos(0) = [ ___ ]\n        Exponent: 1/0² = [ ___ ]\n        Indeterminate form: [ 0/0 / 1^∞ / ∞^0 ]\n\nStep 2: Apply 1^∞ theorem: lim [f(x)]^g(x) = e^{ lim [f(x) - 1] · g(x) }:\n        L = e^K, where K = lim_{x -> 0} [ cos x - [ ___ ] ] · (1 / x²)\n\nStep 3: Express K using half-angle trigonometric identity:\n        1 - cos x = 2 sin²(x/2)  ==>  cos x - 1 = -[ ___ ] sin²(x/2)\n        K = lim_{x -> 0} [ -2 sin²(x/2) ] / x²\n\nStep 4: Regroup into standard limit form [ sin(u) / u ]:\n        K = -2 · lim_{x -> 0} [ sin(x/2) / (x/2) ]² · ( (x/2)² / x² )\n        K = -2 · [ [ ___ ] ]² · ( [ ___ ] / 4 ) = -2 · 1 · (1/4) = -[ ___ ] / [ ___ ]\n\nStep 5: Compute final limit L = e^K:\n        L = e^[ _____ ] = 1 / √e",
        "completion_key": "Step 1: 1; ∞; 1^∞\nStep 2: 1\nStep 3: 2\nStep 4: 1; 1; 1; 2 (-1/2)\nStep 5: -1/2"
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-LIM-01",
        "tier": "Foundation / CBSE",
        "description": "Basic algebraic limits via factorization and rationalization, standard limits (x^n-a^n)/(x-a) and sin(x)/x, left/right hand limit tests for continuity."
      },
      {
        "family_id": "FAMILY-LIM-02",
        "tier": "Olympiad / IOQM",
        "description": "Cesàro-Stolz theorem for sequence limits, bounding sums via Riemann integration lim sum 1/n f(r/n), and functional equation limits."
      },
      {
        "family_id": "FAMILY-LIM-03",
        "tier": "JEE Main",
        "description": "Trigonometric limits with compound angles, exponential and logarithmic limits lim (e^x-1)/x = 1, evaluation of 1^∞ forms, L'Hôpital's Rule iterations."
      },
      {
        "family_id": "FAMILY-LIM-04",
        "tier": "JEE Advanced",
        "description": "Limits involving greatest integer functions floor(x), fractional part {x}, series expansions with non-canceling higher-order differentials, and asymptotic order analysis."
      }
    ]
  },
  {
    "gate_id": "MATH-PERM-COMB",
    "title": "Combinatorics, Permutations & Counting Invariants",
    "section_number": 14,
    "domain": "Combinatorics & Discrete Mathematics",
    "grade_level": "Grade 11–12",
    "exam_families": [
      "CBSE",
      "IOQM",
      "JEE Main",
      "JEE Advanced"
    ],
    "preconditions": [
      "**Strict Discrete Domain Invariant**: $n, r \\in \\mathbb{N}_0$ with $0 \\le r \\le n$. Factorial $n! = \\prod_{k=1}^n k$ with the axiomatic definition $0! \\equiv 1$ (the unique number of ways to order an empty set $\\emptyset$).",
      "**Disjoint Case Mutual Exclusivity (Addition Principle)**: If events $A_1, \\dots, A_k$ are pairwise mutually exclusive ($A_i \\cap A_j = \\emptyset$ for $i \\neq j$), the total number of ways to perform any one event is $\\sum |A_i|$.",
      "**Order Sensitivity Trichotomy**:"
    ],
    "atoms": [
      {
        "atom_id": "ATOM-COMB-01",
        "atom_type": "CONCEPT",
        "description": "Fundamental Principle of Counting (FPC):\n  - Multiplication rule: If operation 1 has $m$ outcomes and operation 2 has $n$ independent outcomes, the composite sequential operation has $m \\times n$ outcomes.\n  - Addition rule: If operation can be done via mutually exclusive pathways, total outcomes is $m + n$."
      },
      {
        "atom_id": "ATOM-COMB-02",
        "atom_type": "INVARIANT",
        "description": "Pascal's Combination Recurrence: $\\binom{n}{r} + \\binom{n}{r-1} = \\binom{n+1}{r}$ for all $1 \\le r \\le n$. Symmetric property: $\\binom{n}{r} = \\binom{n}{n-r}$."
      },
      {
        "atom_id": "ATOM-COMB-03",
        "atom_type": "PROCEDURE",
        "description": "Stars and Bars Multiset Partition Theorem: The number of non-negative integer solutions to $x_1 + x_2 + \\dots + x_k = n$ ($x_i \\ge 0$) is $\\binom{n + k - 1}{k - 1}$. For strictly positive integer solutions ($x_i \\ge 1$), it is $\\binom{n - 1}{k - 1}$."
      },
      {
        "atom_id": "ATOM-COMB-04",
        "atom_type": "RELATION",
        "description": "Circular Permutation Reduction: The number of distinct circular arrangements of $n$ distinct objects is $(n-1)!$. If clockwise and counter-clockwise arrangements are indistinguishable (e.g. necklaces/garlands), it is $\\frac{(n-1)!}{2}$."
      },
      {
        "atom_id": "ATOM-COMB-05",
        "atom_type": "STRATEGY",
        "description": "Grouping / String and Gap Methods:\n  - *String method* (objects must be together): Bundle required items into a single mega-element and multiply by internal permutations.\n  - *Gap method* (no two objects may be together): Arrange remaining items first, then place constrained items into the available inter-item gaps."
      }
    ],
    "misconceptions": [
      {
        "name": "Confusing Addition and Multiplication Rules",
        "flawed_action": "If a task requires choosing a shirt (3 colors) AND a tie (4 colors), calculating $3 + 4 = 7$.",
        "diagnostic_cue": "When actions occur *in conjunction* (successively/jointly), the outcomes multiply: $3 \\times 4 = 12$. Addition applies only to *alternative, mutually exclusive* choices (either a shirt OR a tie)."
      },
      {
        "name": "Overcounting via Independent Sequential Selections",
        "flawed_action": "Selecting 4 people from 10 including at least 1 woman (from 4 women) by picking 1 woman ($\\binom{4}{1}$) and then any 3 from the remaining 9 ($\\binom{9}{3}$).",
        "diagnostic_cue": "Sequential picking labels the chosen elements as \"the first woman\" and \"subsequent people\", creating artificial ordering among women and drastically overcounting. Use complementary counting: Total $-$ No Women $= \\binom{10}{4} - \\binom{6}{4}$."
      },
      {
        "name": "Dividing by 2 for General Circular Arrangements",
        "flawed_action": "Dividing by 2 when seating people around a round table.",
        "diagnostic_cue": "People have distinct left and right orientations; rotating a table does not flip left and right. Only unoriented physical loops that can be flipped over in 3D (like beads on a necklace) divide by 2: $\\frac{(n-1)!}{2}$."
      }
    ],
    "ttus": [
      {
        "ttu_id": "TTU-COMB-01",
        "title": "Incomplete Complementary Counting & Gap Method Scaffold",
        "role": "Core1A $\\to$ Core1B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: In how many ways can 5 boys and 4 girls be seated in a row such that no two girls are together?\n\nStep 1: Identify method: Constrained items (girls) cannot be adjacent ==> Use [ Gap Method / String Method ].\nStep 2: Arrange the unconstrained items (5 boys) first:\n        Number of ways to seat 5 boys in a row: 5! = [ ___ ]\n\nStep 3: Count available gaps created by 5 boys:\n        _ B1 _ B2 _ B3 _ B4 _ B5 _\n        Number of available gaps = 5 + 1 = [ ___ ] gaps.\n\nStep 4: Select and arrange 4 girls in the available gaps:\n        Number of ways to choose 4 gaps out of 6 and arrange 4 girls:\n        P(6, 4) = 6! / (6 - 4)! = 6! / [ ___ ]! = (6 · 5 · 4 · 3 · 2 · 1) / 2 = [ ___ ]\n\nStep 5: Apply Fundamental Multiplication Principle:\n        Total arrangements = (ways to arrange boys) · (ways to place girls in gaps)\n                           = [ ___ ] · [ ___ ] = [ ___ ]",
        "completion_key": "Step 1: Gap Method\nStep 2: 120\nStep 3: 6\nStep 4: 2; 360\nStep 5: 120; 360; 43200"
      },
      {
        "ttu_id": "TTU-COMB-02",
        "title": "Stars and Bars Multiset Partitioning Model",
        "role": "Core2A $\\to$ Core2B",
        "kind": "RECONSTRUCTABLE_SCAFFOLD",
        "viewport": "x ∈ [-5, 5], y ∈ [-5, 5]",
        "scaffold": "Task: Find the number of non-negative integer solutions to x₁ + x₂ + x₃ + x₄ = 12.\n      Also find the number of strictly positive integer solutions.\n\nCase A: Non-negative integer solutions (x_i ≥ 0):\nStep 1: Identify items n and categories k:\n        n (stars) = [ ___ ],   k (variables) = [ ___ ]\nStep 2: Apply Stars and Bars Theorem 1:\n        Total solutions = C(n + k - 1, k - 1)\n                        = C(12 + 4 - 1, 4 - 1)\n                        = C([ ___ ], [ ___ ])\nStep 3: Calculate numerical value:\n        C(15, 3) = (15 · 14 · 13) / (3 · 2 · 1) = (5 · 7 · 13) = [ ___ ]\n\nCase B: Strictly positive integer solutions (x_i ≥ 1):\nStep 4: Apply Stars and Bars Theorem 2:\n        Total solutions = C(n - 1, k - 1)\n                        = C(12 - 1, 4 - 1)\n                        = C([ ___ ], [ ___ ])\nStep 5: Calculate numerical value:\n        C(11, 3) = (11 · 10 · 9) / (3 · 2 · 1) = (11 · 5 · 3) = [ ___ ]",
        "completion_key": "Case A:\nStep 1: 12; 4\nStep 2: 15; 3\nStep 3: 455\nCase B:\nStep 4: 11; 3\nStep 5: 165"
      }
    ],
    "families": [
      {
        "family_id": "FAMILY-COMB-01",
        "tier": "Foundation / CBSE",
        "description": "Basic factorial arithmetic, evaluation of nPr and nCr, word arrangements with repeats (e.g. MATHEMATICS), formation of numbers from digits."
      },
      {
        "family_id": "FAMILY-COMB-02",
        "tier": "Olympiad / IOQM",
        "description": "Principle of Inclusion-Exclusion (PIE), derangements D_n, double counting proofs, Catalan numbers C_n = 1/(n+1) C(2n, n), Pigeonhole Principle."
      },
      {
        "family_id": "FAMILY-COMB-03",
        "tier": "JEE Main",
        "description": "Multiset distribution of identical objects (stars and bars), grouping into heaps (dividing by p!), rank of word in dictionary, sum of digits formed."
      },
      {
        "family_id": "FAMILY-COMB-04",
        "tier": "JEE Advanced",
        "description": "Generating functions for integer partitions, Burnside's Lemma for rotational symmetries, grid walk lattice paths avoiding boundary y = x."
      }
    ]
  }
];
