#!/usr/bin/env python3
"""Authored Motion pilot. Content edits are explicit and reviewable here and in JSON."""
import json,copy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
C=['PHY-MOT-DIST-01','PHY-MOT-DISP-01','PHY-MOT-VTAREA-01','PHY-MOT-VTDIST-01']
# Crosswalk to the canonical Motion source authority (Motion_Source_Coverage_Map.md): CB1 = Position,
# Distance and Displacement; CB12 = graphs. Required by validate_v2.py's concept crosswalk check.
CANON={'PHY-MOT-DIST-01':'CB1','PHY-MOT-DISP-01':'CB1','PHY-MOT-VTAREA-01':'CB12','PHY-MOT-VTDIST-01':'CB12'}
def route(id,positions,lo=-2,hi=8,labels=None,disp=False,ticks=None):
 d=dict(id=id,kind='numberline',dependency_class='NUMBER_LINE',status='FINAL',range=[lo,hi],positions=positions,displacement=disp)
 if labels:d['leg_labels']=labels
 if ticks:d['ticks']=ticks
 return d
def graph(id,segments,trange=None,vrange=None,shade=False):
 tmax=max(s[2] for s in segments);mn=min(0,min(min(s[1],s[3]) for s in segments));mx=max(1,max(max(s[1],s[3]) for s in segments))
 d=dict(id=id,kind='vt',dependency_class='GRAPH',status='FINAL',segments=segments,trange=trange or [0,tmax],vrange=vrange or [mn-1,mx+1],tticks=sorted(set([0]+[s[0] for s in segments]+[s[2] for s in segments])),vticks=sorted(set([0]+[s[1] for s in segments]+[s[3] for s in segments])),shade=shade)
 return d
def B(role,text):return dict(role=role,text=text)
def lesson(id,title,kicker,intro,fig,caption,blocks,takeaway,concepts):
 return dict(id=id,title=title,kicker=kicker,intro=intro,figure=fig,caption=caption,blocks=blocks,takeaway=takeaway,concept_ids=concepts,source_refs=['AUTHOR-MOTION-V2'])
def Q(n,band,question,primary,recap,why,method,answer,keep,hints,repair,fig=None,task_type='Apply',workspace='Show the route or working that makes your answer clear.',numeric=None):
 # task_type is the cognitive-task badge (what the learner must DO), not difficulty (grade9 router rule 3).
 # The pilot has no source analysis, independent expert calibration, or learner-performance data, so it
 # deliberately publishes no numeric difficulty vector. Inferring the vector from task_type would merely
 # relabel the same heuristic. A later qualified review may populate it and update difficulty_source/QA.
 # Callers keep writing hints as a plain 3-string [H1,H2,H3] list in reading order; tagging happens
 # once here so the published shape (list[HintStep], tier explicit) never depends on callers getting
 # the order right by convention alone (hint-numbering-unification).
 tagged_hints=[dict(tier=t,text=h) for t,h in zip(['H1','H2','H3'],hints)]
 return dict(id=f'{band}-A{n}',label=f'A{n}',question=question,primary_concept_id=C[primary],secondary_concept_ids=[c for c in C[:2 if primary<2 else 4] if c!=C[primary]] if primary<2 else [C[5-primary]],recap=recap,solution=dict(why=why,method=method,answer=answer,keep=keep),answer=answer,hints=tagged_hints,repair_mode='LOCAL_LESSON',repair_target=repair,figure=fig,task_type=task_type,difficulty_source='AUTHOR_HEURISTIC',workspace=workspace,source_status='ORIGINAL',provenance_class='ORIGINAL_CALIBRATED',source_refs=['AUTHOR-MOTION-V2'],numeric_check=numeric)

# Concept/source/misconception field names below match ../../../shared/grade9-master.schema.json exactly
# (concept_id/title/prerequisites/mastery_path, source_id/title/provenance_class, the misconception object
# shape) so this file is a compatible extension per grade9-workflow.md S12, not a parallel schema. Physics-
# specific extras (claim, canonical_concept_id) ride alongside via the master schema's additionalProperties.
TITLES={'PHY-MOT-DIST-01':'Distance','PHY-MOT-DISP-01':'Displacement','PHY-MOT-VTAREA-01':'Signed v-t Area (Displacement)','PHY-MOT-VTDIST-01':'v-t Area Magnitudes (Distance)'}
# VTAREA/VTDIST (graph reading) build on DIST/DISP (endpoint reasoning) being already understood; DIST/DISP
# are foundational within this two-topic pilot.
PREREQ={'PHY-MOT-DIST-01':[],'PHY-MOT-DISP-01':[],'PHY-MOT-VTAREA-01':['PHY-MOT-DIST-01','PHY-MOT-DISP-01'],'PHY-MOT-VTDIST-01':['PHY-MOT-DIST-01','PHY-MOT-DISP-01']}
# Grounded in grade9-physics-subtopic-book-builder's own high-priority Motion misconception list ("distance
# = displacement", "graph height confused with slope/area"), in the master-schema misconception object shape.
MISCONCEPTIONS=[
 dict(id='M-MOT-01',wrong_model='Distance and displacement are the same quantity.',
      observable_error="A learner reports total path length for a 'find the displacement' question, or vice versa.",
      diagnostic_question='A student walks 6 m right then 2 m left. Ask separately: how much ground did they cover, and how far are they from the start?',
      repair_explanation='Distance adds every path length walked, with no direction; displacement is only the change from initial to final position. They agree only when the motion never reverses direction.',
      micro_example='0 m to 6 m to 4 m: distance is 6+2=8 m, but displacement is only 4-0=+4 m.',
      transfer_check='Give a return journey with a different turning point and ask for both quantities separately.'),
 dict(id='M-MOT-02',wrong_model='The height of a velocity-time graph directly gives distance travelled.',
      observable_error='A learner reads off the peak/final velocity value and reports it as the distance, instead of computing the area under the graph.',
      diagnostic_question='Show a v-t graph with a changing velocity and ask what the height of the line represents versus what the shaded region represents.',
      repair_explanation='Graph height is velocity, not distance. Distance/displacement is the area enclosed between the line and the time axis, split at every sign change for distance.',
      micro_example='A constant +3 m/s line for 4 s has height 3 m/s, but the enclosed area (and the actual displacement) is 12 m.',
      transfer_check='Give a triangular (accelerating) v-t graph and ask the learner to justify why the answer is not simply the final velocity.'),
]
def base(band):
 return dict(schema_version='2.0',edition='2.0.0',title='Motion · '+('Build the picture' if band=='B30' else 'Reason and transfer'),band=band,learner_label='Build the picture' if band=='B30' else 'Reason and transfer',product='core',status='FOR_USER_REVIEW',
  project=dict(grade=9,subject='Physics',chapter='Motion',target_level=band,core_question_count=8,challenge_question_count=0,version='2.0.0'),
  grade_scope={'intended_grade':9,'supported_authoring_grades':[9,10,11],'syllabus_status':'SELECTED_FOUNDATION_TOPICS_NOT_BOARD_CERTIFIED','exclusions':['full Motion chapter','acceleration calculations','vertical motion','calculus']},placement={'basis':'user-requested provisional support profile','measured':False},
  concepts=[{'concept_id':c,'title':TITLES[c],'claim':s,'canonical_concept_id':CANON[c],'prerequisites':PREREQ[c],'misconception_ids':['M-MOT-01'] if c in ('PHY-MOT-DIST-01','PHY-MOT-DISP-01') else ['M-MOT-02']} for c,s in zip(C,['Distance adds all path lengths and is non-negative.','In one dimension, displacement is final minus initial position in a declared positive direction.','Signed area between velocity–time graph and time axis gives displacement over the interval.','Distance is the sum of positive area magnitudes, splitting at every sign change.'])],
  canonical_concept_registry={'registry_id':'MOTION-CB-V1','source_locator':'Grade 9/Physics/Motion/motion_source_map.yaml#concepts','source_sha256':'7e67b862407d8e09f75c5dfd8d771a753c7e63347903892b04beaa881c312645','allowed_ids':['CB'+str(i) for i in range(13)]},
  topic_ids=['PHY-MOT-M01','PHY-MOT-M02'],frozen_questions=8,lessons=[],questions=[],lesson_ids=[],
  sources=[{'source_id':'AUTHOR-MOTION-V2','title':'Original Motion pilot examples','provenance_class':'ORIGINAL_CALIBRATED','notes':'Original examples and diagrams authored for this two-topic pilot. Not PYQs.'}],
  misconceptions=copy.deepcopy(MISCONCEPTIONS),mixed_tests=[],
  # pdf_render_checked/pdf_links_checked are intentionally omitted here (not set to null - the master
  # schema types them strictly boolean when present): unknown at authoring time, before render_v2.py/
  # audit_v2.py run against this exact JSON. Fill them from audit_v2.py's actual output, not by hand.
  qa=dict(source_qc_complete=True,answers_verified=False,concept_links_verified=True,difficulty_checked=False,
   notes=['Numeric answers are independently recomputed by validate_v2.py (see numerically_recomputed count); qualitative-only answers rely on author review, not independent recomputation.',
    'pdf_render_checked/pdf_links_checked should be filled from audit_v2.py output against the actually rendered PDF, not hand-set here.',
    'Classroom/psychometric calibration NOT_RUN.']))

b30=base('B30')
b30['lessons']=[
lesson('B30-L1','First, locate the learner on the line','1 · Distance and displacement','Imagine a straight corridor. We choose a door as 0 m and right as positive.',route('30-F1',[0,4],-3,6,['4 m right'],ticks=[-3,-2,-1,0,1,2,3,4,5,6]),'The numbers are positions measured from the door. They are not distances already walked.',[
B('heading','What does +4 m tell us?'),B('body','It says where you are: 4 m to the right of the door. A position of −2 m means 2 m to its left.'),B('body','The symbol <i>x</i> means position. The sign tells us which side of our chosen zero we mean.'),B('heading','Move your finger'),B('body','Trace from 0 to +4. Then trace back to 0. The second move goes left, even though every point along it is at 0 m or above.')],
'Say it aloud: position tells me where I am. The direction of my movement tells me which way I am going.',C[:2]),
lesson('B30-L2','One journey, two useful questions','1 · See the whole path and the endpoints','Start at 0 m, walk 6 m right, then walk 2 m left.',route('30-F2',[0,6,4],0,8,['6 m right','2 m left'],True),'The solid return leg is still part of the path. The dashed arrow joins only start and finish.',[
B('heading','How much ground did you cover?'),B('body','Your feet travelled both parts. Add their lengths.'),B('equation','Distance = 6 + 2 = 8 m'),B('heading','What changed from start to finish?'),B('body','You finish 4 m to the right of where you started. That change is displacement.'),B('equation','Displacement = +4 m'),B('body','Distance has no direction. In a straight line, the sign of displacement gives its direction.')],
'Keep the two questions separate: “How much path?” → distance. “What change from the start?” → displacement.',C[:2]),
lesson('B30-L3','Your starting position matters','1 · Build the rule from a picture','Start at +2 m, go to +7 m, then return to +4 m.',route('30-F3',[2,7,4],0,8,['5 m right','3 m left'],True),'The finish is +4 m, but the change from +2 m to +4 m is only +2 m.',[
B('heading','Read the path first'),B('equation','Distance = 5 + 3 = 8 m'),B('heading','Now compare the endpoints'),B('body','A change is the new value minus the old value. Here, final position minus initial position gives:'),B('equation','Displacement = +4 − (+2)'),B('equation','= +2 m  (right)'),B('body','A useful check: the size of the displacement cannot exceed the total path length.')],
'If you return to your start, the endpoint change is zero. Your walking is not erased: distance still counts every part. Try A1–A4 next.',C[:2]),
lesson('B30-L4','A velocity–time graph tells a story','2 · Read the axes before calculating','Choose right as positive. Read the graph from left to right as time passes.',graph('30-F4',[[0,3,4,3],[4,-1,6,-1]]),'The horizontal coordinate is time, not position. The line is not the shape of a road.',[
B('heading','First four seconds'),B('body','The line stays at +3 m/s. This means the object moves 3 m right in each second.'),B('heading','Next two seconds'),B('body','The line is at −1 m/s. The object now moves 1 m left in each second. Its speed is 1 m/s.'),B('body','This interval lasts 6 − 4 = 2 s. Always subtract the two time readings.'),B('body','The abrupt switch is an idealisation. It contributes no extra time or distance.')],
'A horizontal line above zero means steady motion. A line on v = 0 means rest. Below zero means motion in the chosen negative direction.',C[2:]),
lesson('B30-L5','Why does graph area give a change in position?','2 · Build the rectangle, then the rule','At +3 m/s, each second adds another 3 m of rightward movement.',dict(id='30-F5',kind='tiles',dependency_class='DIAGRAM',status='FINAL',cols=4,rows=3),'Four one-second columns make 12 m. This is the +3 m/s part of the previous graph.',[
B('heading','Count what happens each second'),B('equation','3 + 3 + 3 + 3 = 12 m'),B('body','Adding the same change four times is multiplication.'),B('equation','Change = velocity × duration'),B('body','On a v–t graph, height is velocity and width is duration. Their product is the rectangle area.'),B('equation','(+3 m/s) × (4 s) = +12 m'),B('body','The seconds cancel, leaving metres. This rectangle rule requires constant velocity on the interval.')],
'Do not use the final velocity for an entire interval when velocity changes. In that case, use the actual area under the graph.',C[2:]),
lesson('B30-L6','A return journey counts in two different ways','2 · Give area its physical meaning','Use the same graph: +3 m/s for 4 s, then −1 m/s for 2 s.',graph('30-F6',[[0,3,4,3],[4,-1,6,-1]],shade=True),'Above zero adds rightward change. Below zero adds leftward change. Neither part is “negative walking”.',[
B('heading','First find each change'),B('body','Rightward part: (+3) × 4 = +12 m.<br/>Leftward part: (−1) × 2 = −2 m.'),B('heading','Combine the signed changes'),B('equation','Displacement = 12 − 2 = +10 m'),B('heading','Count all the movement'),B('equation','Distance = 12 + 2 = 14 m'),B('body','If you started at +5 m, you would finish at +15 m. The displacement would still be +10 m.')],
'A return can cancel an earlier change in position. It cannot cancel distance already travelled. Complete the two areas in A6 yourself.',C[2:]),
lesson('B30-L7','When velocity rises steadily, use a triangle','2 · Extend the same idea carefully','Velocity rises in a straight line from 0 to +4 m/s over 4 s.',graph('30-F7',[[0,0,4,4]],shade=True),'The sloping line cuts a 4 s by 4 m/s rectangle into two equal triangles.',[
B('heading','Why not 4 × 4?'),B('body','That would describe +4 m/s for all four seconds. Here the object starts at rest and builds up speed.'),B('heading','Take half of the rectangle'),B('equation','Area = ½ × 4 × 4 = 8 m'),B('body','The ½ comes from the triangle, not from a special motion formula.'),B('body','All the graph lies at or above zero. So displacement is +8 m and distance is 8 m.'),B('body','Use the triangle only when the graph is straight over that interval.')],
'You can now explain rectangles and triangles from their shapes. If a graph goes below zero, split it at zero before combining the areas.',C[2:])]

def common_questions(band):
 return [
Q(1,band,'Start at +1 m. Walk 5 m left, then 3 m right. Find the final position, distance and displacement.',1,'Start +1 m; 5 m left, then 3 m right.', 'Position changes carry direction; path lengths do not.','Track the walk step by step: start at +1 m, walk 5 m left to reach 1 − 5, then walk 3 m right to reach the final position, 1 − 5 + 3. Distance simply adds both leg lengths, 5 + 3, while displacement compares only the final position to the start, −1 − (+1).','Final position −1 m; distance 8 m; displacement −2 m (left).','The final coordinate is not automatically the displacement.', ['Keep the starting coordinate separate from the lengths walked.','Mark the start, the turning point and the finish on a number line.','The turning point is at +1 − 5 m. Find the finish next.'],band+'-L3' if band=='B30' else band+'-L1',workspace='Start → turning point → finish\nFinal position: ____\nDistance: ____   Displacement: ____',numeric={'kind':'route','positions':[1,-4,-1],'distance':8,'displacement':-2}),
Q(2,band,'An object moves from −2 m to +5 m without reversing. Find its distance and displacement. Explain the signs.',0,'Move from −2 m to +5 m with no reversal.','The route goes 2 m to zero and another 5 m right.','Distance adds the two legs of the actual path travelled: 2 m to reach zero, then 5 m more to +5 m, giving 2 + 5. Displacement instead compares only the two endpoints, final position minus initial position: +5 − (−2).','Distance 7 m; displacement +7 m (right).','Equal distance and displacement size require no reversal in this straight-line journey.', ['Crossing the origin does not mean reversing direction.','Draw −2, 0 and +5 in order along the line.','The first part of the path, from −2 m to 0 m, is 2 m.'],band+'-L1',workspace='Sketch the line and explain why crossing zero is not a turn.',numeric={'kind':'route','positions':[-2,5],'distance':7,'displacement':7}),
Q(3,band,'Two students start at 0 m and finish at +4 m. Must they have travelled the same distance? Draw two journeys to support your answer.',0,'Same start 0 m and finish +4 m; compare possible distances.','Endpoints fix displacement but leave the path undecided.','One can go directly 0 → +4. Another can go 0 → +7 → +4. Their paths are 4 m and 7 + 3 m.','No. These distances are 4 m and 10 m; both displacements are +4 m.','A drawing can disprove an “always” claim.', ['The question fixes the endpoints, not the route.','Draw one direct route and one route with a turn.','For the turning route, choose a turning point beyond +4 m.'],band+'-L2' if band=='B30' else band+'-L1',task_type='Explain',workspace='Draw and label two routes. Keep the endpoints the same.'),
Q(4,band,'A student walks 7 m right and then 3 m left. Find distance and displacement, taking right as positive.',1,'Walk 7 m right, then 3 m left.','Both legs count towards distance, while leftward motion reduces the rightward change.','Both legs of the walk add to the total distance regardless of direction: 7 + 3. For displacement, keep the sign of each leg since right is positive; the rightward leg contributes +7 m and the leftward leg contributes −3 m, so add the signed changes.','Distance 10 m; displacement +4 m (right).','Separate total path from net change.', ['The student reverses direction after the first leg.','Use a path line and a separate start-to-finish arrow.','Add 7 m and 3 m to begin the distance calculation.'],band+'-L2' if band=='B30' else band+'-L1',numeric={'kind':'route','positions':[0,7,4],'distance':10,'displacement':4}),
Q(5,band,'An object moves at +5 m/s for 3 s, then at −2 m/s for 2 s. Find displacement and distance for the whole journey.',2,'Velocity +5 m/s for 3 s, then −2 m/s for 2 s.','Each interval has constant velocity, so its signed area is velocity × duration.','The changes are +5 × 3 = +15 m and −2 × 2 = −4 m. Add with signs for displacement; add sizes for distance.','Displacement +11 m; distance 19 m. Check: 19 ≥ 11.','Negative velocity gives negative displacement, not negative distance.', ['One interval is rightward and one is leftward.','Draw two velocity–time rectangles on opposite sides of zero.','The first signed area is (+5 m/s) × (3 s).'],band+'-L6' if band=='B30' else band+'-L2',numeric={'kind':'vt','segments':[[0,5,3,5],[3,-2,5,-2]],'distance':19,'displacement':11}),
Q(6,band,'Use the graph to find displacement and distance from 0 s to 5 s. Give a physical meaning for each area.',3,'Graph: +4 m/s from 0–2 s, then −2 m/s from 2–5 s.','Graph widths are durations. The second width is 5 − 2 = 3 s.','Signed areas are +4 × 2 = +8 m and −2 × 3 = −6 m. For distance count both path lengths.','Displacement +2 m; distance 14 m. The parts mean 8 m right and 6 m left.','Read each width from its endpoints before multiplying.', ['Read the duration of each horizontal segment.','Separate the two rectangular regions at t = 2 s.','For the first region, write (+4) × (2 − 0).'],band+'-L6' if band=='B30' else band+'-L2',fig=graph(band+'-A6-F',[[0,4,2,4],[2,-2,5,-2]]),numeric={'kind':'vt','segments':[[0,4,2,4],[2,-2,5,-2]],'distance':14,'displacement':2}),
Q(7,band,'A constant velocity of +2.5 m/s is shown from 0 s to 8 s. Find displacement and distance. Why do their sizes agree?',2,'Constant velocity +2.5 m/s from 0–8 s.','The graph is one positive rectangle; there is no reverse motion.','Signed area = (+2.5 m/s) × (8 s) = +20 m. The same area size is the path length.','Displacement +20 m; distance 20 m. Their sizes agree because direction does not reverse.','A constant positive velocity produces steadily increasing position.', ['The velocity stays on one side of zero.','Draw the rectangle and label height and width with units.','Write area = (+2.5 m/s) × (8 s).'],band+'-L5' if band=='B30' else band+'-L2',numeric={'kind':'vt','segments':[[0,2.5,8,2.5]],'distance':20,'displacement':20}),
Q(8,band,'A trolley has the velocity–time graph shown. Find displacement and distance from 0 s to 6 s. Explain why 6 × 6 is unsuitable.',3,'Velocity increases linearly from 0 to +6 m/s in 6 s.','The graph forms a triangle. The trolley does not spend all 6 s at its final velocity.','The triangle is half of a 6 s by 6 m/s rectangle: ½ × 6 × 6 = 18 m.','Displacement +18 m; distance 18 m. The graph never goes below zero.','Choose the shape from the actual graph, not just its final height.', ['The height grows during the interval.','Compare the region with the complete enclosing rectangle.','The rectangle would have area (6 s) × (6 m/s); use the fraction actually occupied.'],band+'-L7' if band=='B30' else band+'-L3',fig=graph(band+'-A8-F',[[0,0,6,6]]),task_type='Connect',numeric={'kind':'vt','segments':[[0,0,6,6]],'distance':18,'displacement':18})]
b30['questions']=dict(anchors=[],core_calibrated=common_questions('B30'),challenges=[])

b80=base('B80')
b80['lessons']=[
lesson('B80-L1','The same path length can end in different places','1 · Distance and displacement','Both journeys start at 0 m and cover 8 m. Compare what changes.',dict(id='80-F1',kind='compare',dependency_class='MIXED',status='FINAL',figures=[dict(route('80-F1a',[0,6,4],0,8,ticks=[0,2,4,6,8]),title='A: 6 m right, then 2 m left'),dict(route('80-F1b',[0,6,8],0,8,ticks=[0,2,4,6,8]),title='B: 6 m right, then 2 m right')]),'In A, part of the route is retraced. In B, every part contributes to the same rightward change.',[
B('heading','Compare the two totals'),B('body','Both distances: 6 + 2 = 8 m.<br/>Displacement A: +6 − 2 = +4 m.<br/>Displacement B: +6 + 2 = +8 m.'),B('heading','Reconstruct the rule'),B('equation','Δx = x<sub>f</sub> − x<sub>i</sub>'),B('body','Δx means change in position; x<sub>i</sub> is the initial position and x<sub>f</sub> the final position.'),B('body','Distance adds path lengths. In one dimension, the size |Δx| cannot exceed that sum. Equality holds if there is no reversal.')],
'Changing the origin changes both coordinates equally, so their difference is unchanged. Reversing the positive axis changes the sign of Δx, but not the distance.',C[:2]),
lesson('B80-L2','Read a graph as accumulated movement','2 · Signed area and total distance','Take right as positive. A constant velocity gives one rectangle of movement.',graph('80-F2',[[0,3,4,3],[4,-1,6,-1]],shade=True),'Areas are +12 m and −2 m. The second width is 6 − 4 = 2 s, not 6 s.',[
B('heading','Build from a constant interval'),B('equation','Δx = v Δt'),B('body','Velocity is signed movement per second; multiplying by elapsed time reconstructs the movement.'),B('body','Thus graph height × width gives displacement. Units: (m/s) × s = m.'),B('body','The abrupt switch at t = 4 s is an idealisation. It contributes no extra time or distance.'),B('equation','Δx = +12 − 2 = +10 m'),B('equation','Distance = 12 + 2 = 14 m'),B('body','Final position still needs a start: x<sub>f</sub> = x<sub>i</sub> + Δx. A v–t graph alone does not provide x<sub>i</sub>.')],
'Keep graph height, slope and area separate: height is velocity; slope is its rate of change; signed area is displacement.',C[2:]),
lesson('B80-L3','A straight segment can cross zero','2 · Split where the direction changes','Velocity falls linearly from +4 m/s at 0 s to −4 m/s at 4 s.',graph('80-F3',[[0,4,2,0],[2,0,4,-4]],shade=True),'Each triangle has base 2 s and height size 4 m/s. The sign changes at 2 s.',[
B('heading','Predict before calculating'),B('body','The two equal area sizes cancel in displacement. Both still count as movement.'),B('equation','Δx = +½(2)(4) − ½(2)(4)'),B('equation','= 0 m'),B('equation','Distance = 4 + 4 = 8 m'),B('body','The ½ comes from triangular geometry. Straight graph segments let us calculate these areas exactly.'),B('body','A zero average velocity can hide substantial movement. Zero displacement does not imply continuous rest.')],
'A zero value at an instant is not sufficient to prove a reversal. Check whether velocity actually changes sign on the two sides of that instant.',C[2:]),
lesson('B80-L4','A stopped interval changes time, not path length','2 · Translate the graph into a journey','A sensor records +6 m/s for 2 s, rest for 1 s, then −3 m/s for 4 s.',graph('80-F4',[[0,6,2,6],[2,0,3,0],[3,-3,7,-3]],shade=True),'Movement: 12 m right, no movement for 1 s, then 12 m left. The return ends at the start.',[
B('heading','Treat each interval honestly'),B('body','The changes are +12 m, 0 m and −12 m. Rest contributes zero area, even though time passes.'),B('body','The vertical jumps at 2 s and 3 s idealise changes that take no time, so they add no area or distance.'),B('equation','Δx = +12 + 0 − 12 = 0 m'),B('equation','Distance = 12 + 0 + 12 = 24 m'),B('heading','Change the starting position'),B('body','Start at +9 m and finish at +9 m. The same areas still give zero displacement and 24 m distance.')],
'Check a solution using both representations: a signed-area calculation and a right–stop–left motion sketch must tell the same story.',C[2:]),
lesson('B80-L5','Why the final height can mislead you','2 · Choose a model, then test it','Velocity rises linearly from 0 to +6 m/s over 6 s.',graph('80-F5',[[0,0,6,6]],shade=True),'The actual area is half the rectangle formed by the final velocity and the full duration.',[
B('heading','Test the tempting shortcut'),B('body','Using 6 × 6 assumes the object travels at +6 m/s throughout. That contradicts the graph.'),B('equation','Δx = ½ × 6 × 6 = +18 m'),B('body','Distance is 18 m because there is no negative-velocity interval.'),B('heading','What if the line is curved?'),B('body','Do not force it into a triangle. Signed area still represents displacement, but its numerical evaluation needs more information or an approximation.')],
'For independent practice, choose your own diagram. A shorter explanation is acceptable only if the model, signs and physical check remain clear.',C[2:])]
b80['questions']=dict(anchors=[],core_calibrated=common_questions('B80'),challenges=[])
# Band-specific challenges replace repeated elementary items; common A1, A2, A3, A6 remain for comparison.
b80['questions']['core_calibrated'][3]=Q(4,'B80','A particle goes from −3 m to +5 m, then returns to +1 m. Find distance and displacement. A second observer adds 10 m to every coordinate. What changes?',1,'Route −3 → +5 → +1 m; then shift every coordinate by +10 m.','Displacement is a coordinate difference, so a common shift cancels.','Path lengths: 5 − (−3) = 8 m and 5 − 1 = 4 m. Δx = 1 − (−3) = +4 m. Shifted endpoints are +7 m and +11 m.','Distance 12 m and displacement +4 m for both origins. Positions change.','A reference origin changes position values, not a fixed journey.', ['The second observer changes the labels, not the physical journey.','Draw the three positions, then label each with 10 m added.','Compare (1 + 10) − (−3 + 10) with 1 − (−3).'],'B80-L1',task_type='Transfer',numeric={'kind':'route','positions':[-3,5,1],'distance':12,'displacement':4})
b80['questions']['core_calibrated'][4]=Q(5,'B80','Journey A: +3 m/s for 4 s, then +2 m/s for 2 s. Journey B changes only the last velocity to −2 m/s. Find both distances and displacements. Explain what stays the same.',2,'A: +3 for 4 s, then +2 for 2 s. B: last velocity becomes −2 m/s.','Reversing the second velocity changes the area sign, not its size.','First area is +12 m in both. The last area is +4 m in A and −4 m in B. Add signs for displacement and sizes for distance.','A: Δx = +16 m, distance 16 m. B: Δx = +8 m, distance 16 m.','A sign change can alter the endpoint without altering total path.', ['Only the direction of the last interval changes.','Sketch the two graphs with the same scales.','Calculate the common first area: (+3 m/s) × (4 s).'],'B80-L2',task_type='Compare',numeric=None)
b80['questions']['core_calibrated'][6]=Q(7,'B80','A robot has the graph shown and starts at x = +9 m. Find its distance, displacement and final position after 7 s.',3,'Graph +6 m/s for 2 s, rest 1 s, then −3 m/s for 4 s; start +9 m.','Rest adds no displacement. Final position is start plus signed change.','Areas are +12 m, 0 m and −12 m. Distance adds their sizes; displacement adds with signs.','Distance 24 m; displacement 0 m; final position +9 m.','Returning to the start does not mean the robot stayed there.', ['Do not drop the rest interval when locating the last time width.','Pair each graph region with a right, stopped or left motion arrow.','The final region has duration 7 − 3 s.'],'B80-L4',fig=graph('B80-A7-F',[[0,6,2,6],[2,0,3,0],[3,-3,7,-3]]),task_type='Connect',numeric={'kind':'vt','segments':[[0,6,2,6],[2,0,3,0],[3,-3,7,-3]],'distance':24,'displacement':0})
b80['questions']['core_calibrated'][7]=Q(8,'B80','The velocity follows the straight graph shown. Find distance and displacement over 4 s. At what time does the particle reverse direction? Justify this from the graph.',3,'Velocity falls linearly from +6 to −2 m/s over 4 s.','Reversal occurs where velocity changes sign; split the signed area there.','Velocity falls 8 m/s in 4 s. It reaches zero after 6 ÷ 2 = 3 s. Areas: +½ × 3 × 6 = +9 m; −½ × 1 × 2 = −1 m.','Displacement +8 m; distance 10 m; reversal at 3 s.','Equal endpoint signs are not the test; inspect the sign throughout the interval.', ['Locate the zero crossing before calculating areas.','Use the straight-line change to split the graph into two triangles.','The velocity decreases by 8 ÷ 4 m/s each second.'],'B80-L3',fig=graph('B80-A8-F',[[0,6,3,0],[3,0,4,-2]]),task_type='Transfer',numeric={'kind':'vt','segments':[[0,6,3,0],[3,0,4,-2]],'distance':10,'displacement':8})

handout=dict(route=route('HAND-ROUTE',[0,6,4],0,8,ticks=[0,2,4,6,8]),graph=graph('HAND-GRAPH',[[0,3,4,3],[4,-1,6,-1]],shade=True),left=[B('body','<b>Distance:</b> add every path length.<br/><b>Displacement:</b> final position minus initial position. The sign gives direction.'),B('equation','Δx = x<sub>f</sub> − x<sub>i</sub>'),B('body','For this route: distance 8 m; Δx = +4 m.<br/>Check: distance ≥ |Δx|. The bars mean size.'),B('body','<b>Rebuild:</b> choose a zero and positive direction; mark the route; then compare endpoints.')],right=[B('body','<b>Displacement:</b> add signed areas.<br/><b>Distance:</b> add all the area sizes. Split at zero crossings.'),B('equation','Rectangle: v × duration'),B('body','Triangle size: ½ × base × height.<br/>Graph above: Δx = +10 m; distance 14 m.'),B('body','<b>Check:</b> units (m/s) × s = m. A rectangle requires constant velocity; a triangle requires a straight segment.')])
# Second teaching pass: bridge the full example and the complete problem.
g1=lesson('B30-G1','Your turn · Do one small step at a time','1 · Guided practice','Use the empty number line. Mark your answers before checking them.',route('30-G1-F',[],-4,6,ticks=[-4,-3,-2,-1,0,1,2,3,4,5,6]),'Use different marks for a position and a movement arrow.',[
B('heading','G1a · Locate a position'),B('body','Mark −2 m. Is this left or right of the origin?'),B('heading','G1b · Make one movement'),B('body','Start at +1 m. Draw an arrow 3 m left. Label where it ends.'),B('heading','G1c · Compare endpoints'),B('body','A different move starts at −2 m and finishes at +3 m. The arrow points right. Complete: displacement = ___ m right.')],
'Say which number describes a location and which number describes a change. Check the small-step solutions only after you have marked the line.',C[:2])
g1['practice_ids']=['solution-B30-G1']
g2=lesson('B30-G2','Your turn · Complete the area reasoning','2 · Guided practice','The first region is worked for you. Complete the second region and combine them.',graph('30-G2-F',[[0,2,3,2],[3,-1,5,-1]],shade=True),'First region: (+2 m/s) × (3 s) = +6 m of rightward change.',[
B('heading','G2a · Read the second width'),B('body','The interval starts at 3 s and ends at 5 s. Duration = 5 − 3 = ___ s.'),B('heading','G2b · Build its signed area'),B('body','The velocity is −1 m/s.<br/>Second change = (−1) × ___ = ___ m.'),B('heading','G2c · Keep two totals'),B('body','Displacement = +6 + (___) = ___ m.<br/>Distance = 6 + ___ = ___ m.')],
'If a sign is confusing, point to the graph region and say whether the object moves right or left. Then check the small-step solutions.',C[2:])
g2['practice_ids']=['solution-B30-G2']
b30['lessons'].insert(1,g1);b30['lessons'].insert(-1,g2)
b30['guided_solutions']=[dict(id='B30-G1',title='G1 · Positions and one-step changes',text='<b>a.</b> −2 m is 2 m left of the origin.<br/><b>b.</b> From +1 m, moving 3 m left ends at −2 m. The first arrow shows this move.<br/><b>c.</b> From −2 m to +3 m, move 2 m to zero, then 3 m right: displacement = +5 m (right). The second arrow shows this separate move.',figure=route('G1-SOL-F',[1,-2,3],-4,6,ticks=[-4,-2,0,1,3,6])),dict(id='B30-G2',title='G2 · Duration, signed change and total path',text='<b>a.</b> Duration = 5 − 3 = 2 s.<br/><b>b.</b> Second change = (−1) × 2 = −2 m: 2 m left.<br/><b>c.</b> Displacement = +6 + (−2) = +4 m. Distance = 6 + 2 = 8 m.<br/>The leftward part reduces the endpoint change, but still adds 2 m to the path.',figure=graph('G2-SOL-F',[[0,2,3,2],[3,-1,5,-1]],shade=True))]
for q in b30['questions']['core_calibrated'][:2]:
 q['solution_figure']=route(q['id']+'-SOL-F',[1,-4,-1] if q['label']=='A1' else [-2,5],-4,6,ticks=[-4,-2,-1,0,1,3,5,6])
b30['questions']['core_calibrated'][0]['solution']['method']='Start +1 m → turn −4 m → finish −1 m. Distance = 5 + 3 = 8 m. Displacement = −1 − (+1) = −2 m.'
b30['questions']['core_calibrated'][1]['solution']['method']='From −2 m to zero is 2 m; then 5 m more to +5 m. Total change is 7 m right. This explains +5 − (−2) = +7 m.'
# Avoid exposing a worked answer in an allegedly independent B80 question.
b80['questions']['core_calibrated'][6]=Q(7,'B80','A robot has the graph shown and starts at x = −5 m. Find its distance, displacement and final position after 7 s.',3,'Graph +4 m/s for 2 s, rest 1 s, then −1 m/s for 4 s; start −5 m.','Rest adds no displacement. Final position is start plus signed change.','Areas are +8 m, 0 m and −4 m. Add their sizes for distance and their signed values for displacement. Then add the change to −5 m.','Distance 12 m; displacement +4 m; final position −1 m.','A positive displacement can finish at a negative coordinate.', ['The starting coordinate is separate from the displacement.','Pair the graph regions with right, stopped and left motion arrows.','The final region has duration 7 − 3 s.'],'B80-L4',fig=graph('B80-A7-F',[[0,4,2,4],[2,0,3,0],[3,-1,7,-1]]),task_type='Transfer',numeric={'kind':'vt','segments':[[0,4,2,4],[2,0,3,0],[3,-1,7,-1]],'distance':12,'displacement':4})
for p in b30['lessons']:
 if p['id']=='B30-L1':p['title']='First, find your position on the line'
 if p['id']=='B30-G1':
  p['blocks'][-1]['text']='A different move starts at −2 m and finishes at +3 m. The arrow points right. Complete: change in position = ___ m right.'
 if p['id']=='B30-L6':
  p['blocks'][2]['text']='Displacement: signed changes'
  p['blocks'][3]['text']='12 + (−2) = +10 m'
 if p['id']=='B30-L7':
  p['blocks'][-1]['text']='Use ½ × base × height only when the region between the graph and zero line is a triangle.'
  p['takeaway']='Our triangle questions stay above zero. A straight segment away from zero may enclose a rectangle plus a triangle; do not call every sloping region a triangle.'
 if p['id']=='B30-L3':p['practice_ids']=['B30-A1','B30-A3']
 if p['id']=='B30-L7':p['practice_ids']=['B30-A8']
for p in b80['lessons']:
 if p['id']=='B80-L1':p['blocks'][-1]['text']='Distance adds path lengths. The bars in |Δx| mean size without the sign. This size cannot exceed the path length; equality holds with no reversal.'
 if p['id']=='B80-L3':p['blocks'][-1]['text']='Zero displacement can hide substantial movement. Returning to the start does not imply continuous rest.'
 if p['id']=='B80-L5':p['practice_ids']=['B80-A7','B80-A8']
handout['right'][-1]['text']='<b>Check:</b> (m/s) × s = m. Use a rectangle for constant velocity. Use ½ × base × height only for a triangular region; other straight segments may need rectangle + triangle.'
handout['left']=[B('body','<b>Distance:</b> add every path length.<br/><b>Displacement:</b> the signed endpoint change.'),B('equation','Δx = x<sub>f</sub> − x<sub>i</sub>'),B('body','Δx: displacement; x<sub>i</sub>: initial position;<br/>x<sub>f</sub>: final position. Here, distance is 8 m and Δx is +4 m.'),B('body','<b>Check:</b> distance ≥ |Δx|. Bars mean size.<br/><b>Rebuild:</b> trace the path, then compare its endpoints.')]
b30['guided_solutions'][0]['figure']['show_endpoints']=False
b30['guided_solutions'][0]['figure']['leg_labels']=['(b) +1 to −2','(c) −2 to +3']
# Concept-hidden mixed test (finding J): one question per concept, drawn from the shared common_questions.
# render_v2.py publishes this order on a separate attempt surface without task/concept labels, then places
# the diagnosis map after the solutions so it is unavailable during the first attempt.
def mixed_test(band):
 ids=[f'{band}-A1',f'{band}-A2',f'{band}-A5',f'{band}-A6']
 concepts=[C[1],C[0],C[2],C[3]]
 set_id=f'{band}-MIXED-01'
 return dict(test_id=set_id,set_id=set_id,study_mode='MIXED_TRANSFER',concept_hidden=True,question_ids=ids,diagnosis_map=dict(zip(ids,concepts)))
for b in [b30,b80]:
 b['handout']=copy.deepcopy(handout);b['lesson_ids']=[p['id'] for p in b['lessons']]
 b['mixed_tests']=[mixed_test(b['band'])]
 (ROOT/'examples'/('motion_'+b['band']+'_v2.json')).write_text(json.dumps(b,ensure_ascii=False,indent=2),encoding='utf-8',newline='\n')
bank=copy.deepcopy(b80);bank.update(product='question_bank',title='Motion · Optional-hint practice',learner_label='Optional-hint practice',band='B80',lessons=[],lesson_ids=[],handout=None)
for q in bank['questions']['core_calibrated']:
 q['repair_mode']='SELF_CONTAINED';q['repair_target']='SELF_CONTAINED_SOLUTION'
bank['source_claim']='Original-question demonstration of the Examside workflow. No exam attribution or external-corpus completeness claimed.'
(ROOT/'examples/motion_question_bank_v2.json').write_text(json.dumps(bank,ensure_ascii=False,indent=2),encoding='utf-8',newline='\n')
print('Wrote two Core models and original-question bank model.')
