#!/usr/bin/env python3
import argparse, copy, hashlib, json
from pathlib import Path

def canonical(v): return json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False)
def digest(v,field):
    x=copy.deepcopy(v); x.pop(field,None)
    return hashlib.sha256(canonical(x).encode("utf-8")).hexdigest()

BASE_SOURCE_REFS=["P-C/#251","P-D/#252","P-F/#254","Physics SRU methodology"]

ROWS=[
{"id":"PHY-PCK-SYSTEM-REFERENCE-FRAME-v1","caps":["PHY-CAP-FRAME-SIGN-SETUP"],"anchor":"The same motion can have different coordinates for different observers; name the system, origin and axis before assigning signed states.","bridge":"Position, velocity and acceleration describe one system relative to one frame, not free-floating numbers.","validity":"Keep one declared frame through the modeled interval unless a transformation is explicit.","reconstruct":["name the system","choose observer/origin/axis","declare positive direction","bind every signed state to that frame"],"reps":["PHYSICAL_SCENE","SYSTEM_BOUNDARY","SIGNED_AXIS","STATE_TABLE"],"wrong":["writing signed values before choosing an axis","switching frames mid-solution"],"contrast":"Reverse the coordinate axis without changing the physical event; the signs change but the event does not.","transfer":"same motion described from a shifted origin or reversed axis"},
{"id":"PHY-PCK-SIGN-DIRECTION-v1","caps":["PHY-CAP-FRAME-SIGN-SETUP"],"anchor":"A negative velocity means motion opposite the chosen positive axis; it does not by itself mean slowing.","bridge":"Direction comes from the sign of velocity; speeding/slowing comes from how velocity and acceleration directions compare.","validity":"Sign meaning exists only after a frame is declared.","reconstruct":["draw the positive axis","draw velocity and acceleration arrows","translate arrows to signs","compare signs to infer speed change"],"reps":["SIGNED_AXIS","VELOCITY_ARROW","ACCELERATION_ARROW","VT_GRAPH"],"wrong":["negative acceleration always means slowing","negative velocity means negative speed"],"contrast":"With right positive, v<0 and a<0 is speeding left, not slowing.","transfer":"same motion after reversing the positive axis"},
{"id":"PHY-PCK-DISTANCE-DISPLACEMENT-v1","caps":["PHY-CAP-DISTANCE-DISPLACEMENT"],"anchor":"A trip out and back has positive path length but zero net displacement.","bridge":"Distance asks how much path was travelled; displacement asks how the endpoint changed relative to the start.","validity":"Path and endpoints must be defined; a motion word alone does not license a kinematics equation.","reconstruct":["trace the actual path","mark start and finish","compute path length for distance","use endpoint state change for displacement"],"reps":["MOTION_PATH_DIAGRAM","ENDPOINT_CHORD","SIGNED_AXIS"],"wrong":["distance and displacement are synonyms","using a chord as path length"],"contrast":"Two journeys can share endpoints and displacement while having different path lengths.","transfer":"curved path, closed loop and partial-circle variants"},
{"id":"PHY-PCK-AVERAGE-SPEED-WEIGHTING-v1","caps":["PHY-CAP-AVERAGE-SPEED-EQUAL-DISTANCE"],"anchor":"For equal distances, the slower leg lasts longer, so a simple arithmetic mean of speeds has the wrong time weighting.","bridge":"Average speed is the one speed that covers the same total distance in the same total time.","validity":"Use total distance divided by total time; equal-distance and equal-time cases have different weight structures.","reconstruct":["assign equal leg distance d","derive each leg time d/v","sum total distance and total time","form the ratio before cancelling d"],"reps":["RATE_TABLE","DISTANCE_TIME_BARS","TOTAL_DISTANCE_TOTAL_TIME_RATIO"],"wrong":["using arithmetic mean for equal distances","assuming equal distance means equal time"],"contrast":"The same two speeds give different averages under equal-time versus equal-distance travel.","transfer":"unequal-distance legs and repeated cycles"},
{"id":"PHY-PCK-CONSTANT-ACCELERATION-MODEL-GATE-v1","caps":["PHY-CAP-MODEL-VALIDITY-CHECK","PHY-CAP-UNIFORM-ACCELERATION"],"anchor":"A kinematic equation is a compressed description of one model: acceleration must remain constant over the modeled interval.","bridge":"Ask whether constant acceleration is defensible before asking which formula contains the unknown.","validity":"Constant acceleration over the interval is a model gate; split phases when the model changes.","reconstruct":["identify the modeled interval","represent velocity change on a v-t graph","read constant slope as acceleration","derive state change before compressing to equations"],"reps":["MOTION_STRIP","VT_GRAPH","STATE_TABLE","EQUATION_FAMILY"],"wrong":["formula hunting from keywords","using one constant-a model across a phase change"],"contrast":"Identical known symbols do not justify the same equation if one motion has variable acceleration.","transfer":"piecewise acceleration with a model change","eq":["1/2","t^2","v^2"]},
{"id":"PHY-PCK-EQUATION-SELECTION-FIRST-MOVE-v1","caps":["PHY-CAP-FIRST-EQUATION","PHY-CAP-UNIFORM-ACCELERATION"],"anchor":"The first equation is a state-link chosen because it connects known states to the target without introducing an unnecessary unknown.","bridge":"Equation choice follows the known/target structure after model validity, not formula familiarity.","validity":"The constant-acceleration model must already be established.","reconstruct":["label u,v,a,t,s as known or unknown","name the target","choose a relation that avoids an extra unknown","say what that relation means physically","solve and verify"],"reps":["KNOWN_TARGET_STATE_TABLE","VT_GRAPH","KINEMATIC_RELATION_MAP"],"wrong":["choosing the most familiar formula","substituting before fixing signs"],"contrast":"Change only the requested quantity while keeping the same state data; the best first relation can change.","transfer":"stopping, speeding and unknown-time variants","eq":["1/2","t^2","v^2"]},
{"id":"PHY-PCK-STATE-PROPAGATION-PHASES-v1","caps":["PHY-CAP-STATE-PROPAGATE","PHY-CAP-MULTIPHASE-KINEMATICS","PHY-CAP-MOVING-RELEASE"],"anchor":"A new phase starts from the physical state at the end of the old phase; resetting an equation does not reset the body.","bridge":"Terminal state becomes next initial state unless a physical event creates a discontinuity.","validity":"State continuity depends on the boundary event; impulses can change velocity while ordinary release does not.","reconstruct":["mark the phase boundary","write terminal state","identify continuous variables","copy them into the next initial state","select the new phase model"],"reps":["PHASE_TIMELINE","BOUNDARY_STATE_TABLE","STATE_VECTOR_HANDOFF"],"wrong":["resetting phase-2 velocity to zero","carrying the old acceleration after the model changes"],"contrast":"A non-impulsive release changes the force model but not instantaneous velocity.","transfer":"moving-platform release and braking-then-coasting","eq":["sign changes","zero crossings"],"handoff":true},
{"id":"PHY-PCK-NTH-SECOND-INTERVAL-v1","caps":["PHY-CAP-NTH-SECOND-INTERVAL"],"anchor":"The nth second is the interval from n-1 to n, not the whole motion from zero to n.","bridge":"Displacement in the nth second is the cumulative displacement at n minus what had already accumulated at n-1.","validity":"The same motion model must cover both interval endpoints; distance requires extra care if direction reverses.","reconstruct":["write cumulative S(t)","evaluate S(n)","evaluate S(n-1)","subtract to isolate the interval"],"reps":["TIME_AXIS_INTERVAL","CUMULATIVE_S_T_CURVE","DIFFERENCE_BAR"],"wrong":["using S(n) as nth-second displacement","memorizing an nth-second formula without interval meaning"],"contrast":"S(4) includes the first three seconds; the fourth-second contribution is only S(4)-S(3).","transfer":"successive-second ratios and free-fall 1:3:5:7","eq":["nth-second subtraction","1/2","t^2"]},
{"id":"PHY-PCK-STOPPING-DISTANCE-SPEED-SQUARED-v1","caps":["PHY-CAP-UNIFORM-ACCELERATION"],"anchor":"With the same braking acceleration, doubling initial speed makes stopping distance four times as large.","bridge":"The stop condition removes a squared-speed term, so distance scales with u^2 when braking acceleration is fixed.","validity":"The scaling assumes approximately constant braking acceleration.","reconstruct":["set final speed v=0","use or reconstruct v^2=u^2+2as","solve s=-u^2/(2a)","form ratios before substituting numbers"],"reps":["STATE_BEFORE_AFTER","VT_GRAPH_TRIANGLE","V2_U2_2AS_RELATION"],"wrong":["linear speed-distance scaling","dropping the braking sign"],"contrast":"Hold braking acceleration fixed and compare u with 2u before calculation.","transfer":"road-condition comparison and penetration analogues","eq":["v^2","squared velocity"]},
{"id":"PHY-PCK-GRAVITY-CONSTANT-ACCELERATION-v1","caps":["PHY-CAP-FREE-FALL-CONSTANT-G","PHY-CAP-VERTICAL-PROJECTION"],"anchor":"Gravity changes vertical velocity downward every second even while an object is moving upward.","bridge":"g is an acceleration direction, not a speed and not a sign memorized independently of the axis.","validity":"Use local constant g with significant drag neglected.","reconstruct":["choose vertical sign","write a as signed g","map free fall to constant-acceleration motion","propagate the state","interpret the result against the trajectory"],"reps":["VERTICAL_AXIS","VELOCITY_TICKS","VT_GRAPH","STATE_TABLE"],"wrong":["g becomes zero at the top","heavier objects fall faster in the ideal model","changing the sign of g when velocity reverses"],"contrast":"At ascent, apex and descent the velocity changes sign but gravitational acceleration stays downward.","transfer":"Earth/Moon scaling and throw from a height","eq":["1/2","t^2","sign changes","zero crossings"]},
{"id":"PHY-PCK-HIGHEST-POINT-ZERO-V-NONZERO-A-v1","caps":["PHY-CAP-VERTICAL-PROJECTION"],"anchor":"At the highest point vertical velocity is zero for an instant, while gravity still accelerates the object downward.","bridge":"Zero velocity is one instantaneous state; zero acceleration would mean velocity is not changing there.","validity":"Constant-g free flight remains one phase through the apex.","reconstruct":["follow velocity toward zero","identify the v=0 instant","keep a=-g in the fixed axis","show velocity crosses through zero"],"reps":["VERTICAL_TRAJECTORY","VELOCITY_ARROWS","ACCELERATION_ARROW","VT_ZERO_CROSSING"],"wrong":["zero velocity means zero acceleration","treating the top as a rest phase"],"contrast":"If acceleration were zero at the apex, the object could not immediately acquire downward velocity.","transfer":"other turning points with v=0 but a not zero","eq":["zero crossings"]},
{"id":"PHY-PCK-SAME-HEIGHT-TWO-TIMES-v1","caps":["PHY-CAP-VERTICAL-PROJECTION"],"anchor":"A vertically thrown object can visit the same height twice, once upward and once downward.","bridge":"Two positive time roots can be two real events, not duplicate algebraic answers.","validity":"Both roots must lie inside the modeled free-flight time domain.","reconstruct":["write y(t)-y_target=0","recognize the quadratic","solve for roots","map each root to ascent or descent"],"reps":["PARABOLIC_Y_T_GRAPH","VERTICAL_TRAJECTORY","TWO_ROOTS_ON_TIME_AXIS"],"wrong":["discarding the second positive root automatically","assuming same height means same velocity vector"],"contrast":"The same position can occur at two times with opposite vertical velocity directions.","transfer":"same-height speed symmetry and launch from an elevated point","eq":["t^2","two roots","sign changes"]},
{"id":"PHY-PCK-RELATIVE-COMMON-G-CANCELLATION-v1","caps":["PHY-CAP-RELATIVE-ACCELERATION-SAME-G"],"anchor":"If two bodies receive the same downward acceleration, that common acceleration cancels from their relative acceleration.","bridge":"Relative acceleration is the signed difference a_A-a_B; equal g minus equal g is zero.","validity":"Both bodies must share the same g model and frame; drag or extra forces break the cancellation.","reconstruct":["write separate A/B states","align frame and sign","form a_rel=a_A-a_B","cancel the common g","propagate relative motion"],"reps":["TWO_BODY_STATE_TABLE","RELATIVE_POSITION_AXIS","ACCELERATION_ARROWS"],"wrong":["adding accelerations instead of subtracting","using different sign axes for the bodies"],"contrast":"Doubling the same g for both bodies still leaves relative acceleration zero.","transfer":"drop versus upward-thrown body and two falling objects"},
{"id":"PHY-PCK-MOVING-RELEASE-v1","caps":["PHY-CAP-MOVING-RELEASE","PHY-CAP-STATE-PROPAGATE"],"anchor":"A released object keeps the carrier's instantaneous velocity at the release moment; letting go is not stopping.","bridge":"Release changes the constraint and later acceleration model, not the instantaneous velocity unless an impulse acts.","validity":"Velocity is continuous across non-impulsive release; the post-release force model must be selected separately.","reconstruct":["identify carrier velocity just before release","copy it into the released object's initial state","switch to the post-release acceleration model","propagate the new phase"],"reps":["PRE_POST_RELEASE_SNAPSHOT","BOUNDARY_STATE_TABLE","VELOCITY_VECTOR_HANDOFF"],"wrong":["setting released-object initial velocity to zero","keeping carrier acceleration after release"],"contrast":"An object released from an upward-moving balloon initially continues upward in the ground frame.","transfer":"horizontal platform and moving-elevator release","eq":["sign changes"],"handoff":true},
{"id":"PHY-PCK-VT-SIGNED-AREA-v1","caps":["PHY-CAP-VT-SIGNED-AREA"],"anchor":"A thin strip under a velocity-time graph has units velocity×time=displacement; below-axis strips are negative displacement.","bridge":"Signed area gives displacement; adding magnitudes of separate regions gives total distance.","validity":"The graph must be velocity versus time with consistent units.","reconstruct":["partition at zero crossings","compute signed area by region","sum algebraically for displacement","sum magnitudes for distance"],"reps":["MOTION_STORY","VT_GRAPH","SIGNED_AREA_REGIONS","DISPLACEMENT_NUMBER_LINE"],"wrong":["using graph height as displacement","adding every region positively for displacement"],"contrast":"Equal positive and negative areas can give zero displacement but nonzero distance.","transfer":"piecewise v-t return motion","eq":["sign changes","zero crossings"],"graph":true},
{"id":"PHY-PCK-GRAPH-HEIGHT-SLOPE-AREA-v1","caps":["PHY-CAP-REPRESENTATION-TRANSLATE","PHY-CAP-XT-SLOPE-VELOCITY","PHY-CAP-GRAPH-ACCELERATION"],"anchor":"Graph height, slope and area are different operations; their physical meanings depend on the axes and units.","bridge":"On x-t slope is velocity; on v-t height is velocity, slope is acceleration and area is displacement.","validity":"Interpretation is axis-specific; corners and discontinuities need local care.","reconstruct":["read axes and units","name graph height meaning","derive slope units","derive area units","match operation units to the physical quantity"],"reps":["WORDS","MOTION_PICTURE","XT_GRAPH","VT_GRAPH","AT_GRAPH","EQUATION"],"wrong":["treating height, slope and area interchangeably","assuming steeper always means faster"],"contrast":"Identical-shaped x-t and v-t graphs require different slope/area interpretations.","transfer":"piecewise graphs and impossible-graph diagnosis","eq":["sign changes","zero crossings"],"graph":true},
{"id":"PHY-PCK-PHYSICAL-VERIFICATION-v1","caps":["PHY-CAP-MODEL-VALIDITY-CHECK","PHY-CAP-REPRESENTATION-TRANSLATE","PHY-CAP-UNIFORM-ACCELERATION"],"anchor":"A calculation is unfinished until the result fits units, direction, scale, continuity and the physical model.","bridge":"Verification asks whether the answer could belong to the situation, not only whether arithmetic ran without error.","validity":"Dimensional consistency cannot rescue an invalid model.","reconstruct":["check units/dimensions","interpret sign and direction","estimate magnitude","check phase continuity","test limiting/scaling behavior","recheck model conditions"],"reps":["RESULT_WITH_UNITS","SIGN_AXIS","BOUNDARY_CHECK","LIMITING_CASE"],"wrong":["number-only checking","treating a unit check as proof of model validity"],"contrast":"A result can have correct units yet an impossible sign or magnitude.","transfer":"same model in a new story, scale or representation"},
{"id":"PHY-PCK-PROJECTILE-COMPONENTS-v1","caps":["PHY-CAP-PROJECTILE-COMPONENTS"],"anchor":"A projectile has one motion but separate horizontal and vertical component stories linked by the same time.","bridge":"Gravity changes the vertical component; ideal horizontal velocity persists, so total velocity is usually not zero at the apex.","validity":"Neglect drag, use uniform g and one inertial frame.","reconstruct":["decompose initial velocity","write component accelerations","propagate x and y with common time","recombine only if asked"],"reps":["TRAJECTORY","VELOCITY_COMPONENTS","TWO_COMPONENT_STATE_TABLE","XT_YT_GRAPHS"],"wrong":["using g in the horizontal equation","using different times for x and y","calling total velocity zero at apex"],"contrast":"At an oblique-launch apex v_y=0 while v_x remains nonzero in the ideal model.","transfer":"horizontal and oblique launch variants","eq":["zero crossings","t^2"]}
]

def asset(row):
    a={
      "asset_id":row["id"],"version":"1.0.0","schema_version":"1.0.0","subject":"PHYSICS","lifecycle_status":"CANDIDATE",
      "capability_refs":row["caps"],
      "applicability_conditions":["use when this capability is required by the P-F LearnerStudyModel","use for source-grounded Grade-9 Physics teaching rather than formula recall alone"],
      "physical_anchor":row["anchor"],
      "system_frame_setup":{"system_definition":"Name the physical system before calculation.","frame_rule":"Use the frame required by the bound P-F/P-D source obligations.","sign_rule":"Declare and preserve the sign convention before interpreting signed states."},
      "representation_path":row["reps"],
      "ordinary_language_bridge":row["bridge"],
      "model_validity_cue":row["validity"],
      "relation_reconstruction_route":row["reconstruct"],
      "minimal_contrast":{"shared_structure":"Hold the target mechanism fixed while changing only the decisive feature.","wrong_case":row["wrong"][0],"correct_case":row["contrast"],"prediction_prompt":"Predict which description is physically consistent before calculating.","decisive_feature":row["contrast"]},
      "worked_example_family":"BOUND_FROM_STUDY_SCOPE",
      "common_wrong_model":row["wrong"],
      "misconception_discriminator":{"probe":"Present the minimal contrast and require a physical explanation before algebra.","decisive_response":"Learner identifies the decisive physical feature and rejects the wrong model."},
      "repair_route":["return to the physical anchor and representation before equations","contrast the plausible wrong model with the correct model","retry on a new problem-family instance","transfer without the original scaffold"],
      "verification_method":["check units/dimensions and sign/direction where applicable","check magnitude, continuity, limiting behavior and model consistency where applicable"],
      "fading_dimensions":["physical anchor supplied","representation supplied","reconstruction cue supplied","verification cue supplied"],
      "transfer_family":row["transfer"],
      "known_limitations":["applies only under the stated model-validity conditions","does not replace a different P-D problem family when the physical mechanism changes"],
      "equation_features_to_explain":row.get("eq",[]),
      "graph_semantics_required":bool(row.get("graph",False)),
      "state_handoff_required":bool(row.get("handoff",False)),
      "provenance":{"evidence_class":"REPOSITORY_AUTHORITY_PLUS_AI_ASSISTED_DRAFT","source_refs":BASE_SOURCE_REFS,"authoring_origin":"AI_ASSISTED_DRAFT"},
      "review":{"required_dimensions":["SUBJECT","PEDAGOGY"],"status":"PENDING_HUMAN_REVIEW","human_review_evidence_refs":[]},
      "asset_digest":""
    }
    a["asset_digest"]=digest(a,"asset_digest")
    return a

def get_registry():
    r={"registry_id":"PHY-PCK-CANDIDATE-REGISTRY-v1","schema_version":"1.0.0","subject":"PHYSICS","registry_class":"CANDIDATE","asset_documents":[asset(x) for x in ROWS],"registry_digest":""}
    r["registry_digest"]=digest(r,"registry_digest")
    return r

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--out")
    a=ap.parse_args(); r=get_registry()
    text=json.dumps(r,ensure_ascii=False,indent=2,sort_keys=True)+"\n"
    if a.out: Path(a.out).write_text(text,encoding="utf-8")
    else: print(text,end="")
if __name__=="__main__": main()
