from __future__ import annotations
import copy,sys,tempfile,unittest
from pathlib import Path
import yaml
HERE=Path(__file__).resolve();sys.path.insert(0,str(HERE.parents[2]/"scripts"));sys.path.insert(0,str(HERE.parent))
from test_parallel_bootstrap import parallel_repo,ep,dump
from validate_parallel_replan import validate as parallel_replan
from validate_parallel_plan import validate as parallel_plan
from validate_ep_self_contained import validate_ep_data


def checkpoint_a():
    return {"schema_version":"relay-v2.5","checkpoint_id":"CP-A","ep_id":"EP-A","roadmap_basis":{"roadmap_id":"RM-P","revision":"RM-1"},"execution_basis":{"material_ref":"abc"},"implementation_result":{"completed_steps":["STEP-1"],"files_changed":["src/a"]},"acceptance_results":[{"id":"AC-1","status":"PASS"}],"validation_results":[{"id":"TEST-1","status":"PASS","basis_ref":"abc"}],"quality_findings":[],"discoveries":[],"roadmap_reconciliation":{"result":"STATUS_UPDATE"},"successor":{"mode":"JOIN","frontier_work_package":None,"ep_id":None,"parallel_plan":"PLAN-P1","lane_id":"LANE-A","join_id":None,"lanes":[]}}


def serial_replan_repo(root:Path):
    roadmap,plan,state=parallel_repo(root);wps=roadmap["objectives"][0]["phases"][0]["work_packages"];wps[0]["state"]="COMPLETE";wps[0]["execution_status"]="TERMINAL";dump(root/"agents/relay/roadmap/OVERALL_ROADMAP.yaml",roadmap);dump(root/"agents/relay/checkpoints/CP-A.yaml",checkpoint_a())
    unresolved=[{"id":"AC-1","state":"NOT_RUN","basis":["EP-B"]}];evidence=[{"id":"TEST-1","status":"NOT_RUN","basis_ref":"abc","reason":"Original lane route became invalid before execution."}]
    replacement=ep("EP-B2","agent/lane-b2","WP-B","src/b");replacement["identity"]["previous_replan"]="REPLAN-P2";replacement["replan_inheritance"]={"from_replan":"REPLAN-P2","unresolved_acceptance":copy.deepcopy(unresolved),"evidence":copy.deepcopy(evidence)};dump(root/"agents/relay/execution-packages/EP-B2.yaml",replacement)
    receipt={"schema_version":"relay-v2.5-parallel-replan","id":"REPLAN-P2","predecessor_plan":{"id":"PLAN-P1","path":"agents/relay/parallel/PLAN-P1.yaml"},"trigger":{"type":"LANE_INVALIDATED","lane_id":"LANE-B","reason":"Lane B route is stale and cannot safely continue.","basis":["DRIFT-B"]},"lane_dispositions":[{"lane_id":"LANE-A","work_package":"WP-A","disposition":"COMPLETE","checkpoint":{"id":"CP-A","path":"agents/relay/checkpoints/CP-A.yaml"}},{"lane_id":"LANE-B","work_package":"WP-B","disposition":"INVALIDATED","basis":["DRIFT-B"],"unresolved_acceptance":copy.deepcopy(unresolved),"evidence":copy.deepcopy(evidence),"transfers":[{"work_package":"WP-B","unresolved_acceptance":copy.deepcopy(unresolved),"evidence":copy.deepcopy(evidence)}]}],"roadmap_reconciliation":{"roadmap_revision":"RM-1","frontier_after":["WP-B"]},"successor_route":{"mode":"SERIAL","work_package":"WP-B","ep_id":"EP-B2","ep_path":"agents/relay/execution-packages/EP-B2.yaml","parallel_plan_id":None,"parallel_plan_path":None}}
    dump(root/"agents/relay/parallel/REPLAN-P2.yaml",receipt)
    state.update({"relay_state":"ACTIVE","current_position":{"objective":"OBJ","phase":"PHASE","work_package":"WP-B","work_packages":[]},"execution_policy":{"mode":"SERIAL"},"active_ep":{"id":"EP-B2","path":"agents/relay/execution-packages/EP-B2.yaml","state":"ACTIVE"},"last_checkpoint":{"id":"NONE","path":None},"predecessor_join":{"id":None,"path":None},"predecessor_replan":{"id":"REPLAN-P2","path":"agents/relay/parallel/REPLAN-P2.yaml"}});state["status_planes"]["execution"].update({"state":"ACTIVE","can_continue":True,"material_authority":"WRITE","next_action":"Execute only replacement EP-B2."});state["projection"].update({"execution_ref":"EP-B2","state":"NOT_REQUIRED","required":False});dump(root/"agents/relay/REPO_STATE.yaml",state);return receipt,replacement


def parallel_replan_repo(root:Path):
    roadmap,old_plan,state=parallel_repo(root);phase=roadmap["objectives"][0]["phases"][0];wps=phase["work_packages"];wps[0]["state"]="COMPLETE";wps[0]["execution_status"]="TERMINAL";wps[1]["state"]="SUPERSEDED";wps[1]["execution_status"]="TERMINAL";wps[2]["state"]="SUPERSEDED";wps[2]["execution_status"]="TERMINAL";wps.extend([{"id":"WP-B1","title":"Replacement B1","state":"ACTIVE","definition":"DETAILED","execution_status":"ACTIVE","depends_on":["WP-A"]},{"id":"WP-B2","title":"Replacement B2","state":"ACTIVE","definition":"DETAILED","execution_status":"ACTIVE","depends_on":["WP-A"]},{"id":"WP-I2","title":"Replacement integration","state":"PLANNED","definition":"DETAILED","execution_status":"WAITING","depends_on":["WP-B1","WP-B2"]}]);dump(root/"agents/relay/roadmap/OVERALL_ROADMAP.yaml",roadmap);dump(root/"agents/relay/checkpoints/CP-A.yaml",checkpoint_a())
    acc1={"id":"AC-B1","state":"NOT_RUN","basis":["EP-B","AC-B1"]};acc2={"id":"AC-B2","state":"NOT_RUN","basis":["EP-B","AC-B2"]};ev1={"id":"TEST-B1","status":"NOT_RUN","basis_ref":"abc","reason":"Old lane invalidated before TEST-B1."};ev2={"id":"TEST-B2","status":"NOT_RUN","basis_ref":"abc","reason":"Old lane invalidated before TEST-B2."};all_acc=[acc1,acc2];all_ev=[ev1,ev2]
    ep1=ep("EP-B1","agent/lane-b1","WP-B1","src/b1");ep2=ep("EP-B2","agent/lane-b2","WP-B2","src/b2")
    for candidate,a,v in ((ep1,[acc1],[ev1]),(ep2,[acc2],[ev2])):candidate["identity"]["previous_replan"]="REPLAN-P2";candidate["replan_inheritance"]={"from_replan":"REPLAN-P2","unresolved_acceptance":copy.deepcopy(a),"evidence":copy.deepcopy(v)}
    dump(root/"agents/relay/execution-packages/EP-B1.yaml",ep1);dump(root/"agents/relay/execution-packages/EP-B2.yaml",ep2)
    new_plan={"schema_version":"relay-v2.5","id":"PLAN-P2","previous_replan":"REPLAN-P2","previous_replan_path":"agents/relay/parallel/REPLAN-P2.yaml","owner_approval":{"approved":True,"authority":"OWNER","source":"OWNER-DECISION-2","approval_token":"APPROVE PARALLEL PLAN-P2"},"ascii_topology":"REPLAN\n +-- B1\n +-- B2\n  \\ /\n INTEGRATE-2","lanes":[{"id":"LANE-B1","state":"ACTIVE","work_package":"WP-B1","ep_id":"EP-B1","ep_path":"agents/relay/execution-packages/EP-B1.yaml","branch":"agent/lane-b1","worktree":"wt-b1","write_domains":["src/b1"],"shared_read_domains":["src/shared"]},{"id":"LANE-B2","state":"ACTIVE","work_package":"WP-B2","ep_id":"EP-B2","ep_path":"agents/relay/execution-packages/EP-B2.yaml","branch":"agent/lane-b2","worktree":"wt-b2","write_domains":["src/b2"],"shared_read_domains":["src/shared"]}],"shared_write_exceptions":[],"integration":{"owner":"OWNER","work_package":"WP-I2","planned_ep_id":"EP-I2","creation_policy":"WHEN_FRONTIER","depends_on_lanes":["LANE-B1","LANE-B2"]},"risks":[{"id":"R2","description":"replacement-lane integration risk"}],"stop_conditions":[{"id":"S2","condition":"replacement lane leaves approved write domain"}]};dump(root/"agents/relay/parallel/PLAN-P2.yaml",new_plan)
    receipt={"schema_version":"relay-v2.5-parallel-replan","id":"REPLAN-P2","predecessor_plan":{"id":"PLAN-P1","path":"agents/relay/parallel/PLAN-P1.yaml"},"trigger":{"type":"LANE_INVALIDATED","lane_id":"LANE-B","reason":"Lane B must split into two independently isolated replacement packages.","basis":["ROADMAP-REVISION-RM-2"]},"lane_dispositions":[{"lane_id":"LANE-A","work_package":"WP-A","disposition":"COMPLETE","checkpoint":{"id":"CP-A","path":"agents/relay/checkpoints/CP-A.yaml"}},{"lane_id":"LANE-B","work_package":"WP-B","disposition":"INVALIDATED","basis":["ROADMAP-REVISION-RM-2"],"unresolved_acceptance":copy.deepcopy(all_acc),"evidence":copy.deepcopy(all_ev),"transfers":[{"work_package":"WP-B1","unresolved_acceptance":copy.deepcopy([acc1]),"evidence":copy.deepcopy([ev1])},{"work_package":"WP-B2","unresolved_acceptance":copy.deepcopy([acc2]),"evidence":copy.deepcopy([ev2])}]}],"roadmap_reconciliation":{"roadmap_revision":"RM-1","frontier_after":["WP-B1","WP-B2"]},"successor_route":{"mode":"PARALLEL","work_package":None,"ep_id":None,"ep_path":None,"parallel_plan_id":"PLAN-P2","parallel_plan_path":"agents/relay/parallel/PLAN-P2.yaml"}};dump(root/"agents/relay/parallel/REPLAN-P2.yaml",receipt)
    state.update({"relay_state":"PARALLEL","current_position":{"objective":"OBJ","phase":"PHASE","work_package":"PARALLEL","work_packages":["WP-B1","WP-B2"]},"execution_policy":{"mode":"OWNER_APPROVED_PARALLEL","parallel_plan":"agents/relay/parallel/PLAN-P2.yaml"},"active_ep":{"id":"PARALLEL_ROUTER","path":None,"state":"ROUTER"},"last_checkpoint":{"id":"NONE","path":None},"predecessor_join":{"id":None,"path":None},"predecessor_replan":{"id":"REPLAN-P2","path":"agents/relay/parallel/REPLAN-P2.yaml"}});state["status_planes"]["execution"].update({"state":"ACTIVE","can_continue":True,"material_authority":"WRITE","next_action":"Execute only the replacement lane matching live route context."});state["projection"].update({"execution_ref":"PLAN-P2","state":"NOT_REQUIRED","required":False});dump(root/"agents/relay/REPO_STATE.yaml",state);return receipt,new_plan,ep1,ep2

class ParallelReplanStressTests(unittest.TestCase):
    def test_partial_lane_invalidation_can_collapse_to_one_serial_replacement(self):
        with tempfile.TemporaryDirectory() as td:root=Path(td);serial_replan_repo(root);self.assertEqual([],parallel_replan(root)[0])
    def test_completed_sibling_checkpoint_cannot_disappear_from_replan(self):
        with tempfile.TemporaryDirectory() as td:root=Path(td);receipt,_=serial_replan_repo(root);receipt["lane_dispositions"]=receipt["lane_dispositions"][1:];dump(root/"agents/relay/parallel/REPLAN-P2.yaml",receipt);self.assertTrue(any("cover every predecessor lane" in x for x in parallel_replan(root)[0]))
    def test_replacement_ep_must_inherit_invalidated_acceptance_and_evidence_exactly(self):
        with tempfile.TemporaryDirectory() as td:root=Path(td);_,replacement=serial_replan_repo(root);replacement["replan_inheritance"]["evidence"][0]["status"]="PASS";dump(root/"agents/relay/execution-packages/EP-B2.yaml",replacement);self.assertTrue(any("inheritance mismatch for evidence" in x for x in parallel_replan(root)[0]))
    def test_replanned_ep_has_one_predecessor_baton(self):
        with tempfile.TemporaryDirectory() as td:root=Path(td);_,replacement=serial_replan_repo(root);replacement["identity"]["previous_checkpoint"]="CP-A";errors=validate_ep_data(root,replacement,"replacement")[0];self.assertTrue(any("only one of previous_checkpoint, previous_join, previous_replan" in x for x in errors))
    def test_invalidated_lane_can_split_exactly_into_new_parallel_frontier(self):
        with tempfile.TemporaryDirectory() as td:root=Path(td);parallel_replan_repo(root);self.assertEqual([],parallel_replan(root)[0]);self.assertEqual([],parallel_plan(root)[0])
    def test_split_transfer_cannot_duplicate_unresolved_evidence(self):
        with tempfile.TemporaryDirectory() as td:root=Path(td);receipt,_,_,_=parallel_replan_repo(root);bad=receipt["lane_dispositions"][1]["transfers"];bad[1]["evidence"]=[copy.deepcopy(bad[0]["evidence"][0])];dump(root/"agents/relay/parallel/REPLAN-P2.yaml",receipt);self.assertTrue(any("evidence transfer partition" in x for x in parallel_replan(root)[0]))
    def test_split_transfer_cannot_upgrade_not_run_to_pass(self):
        with tempfile.TemporaryDirectory() as td:root=Path(td);receipt,_,_,_=parallel_replan_repo(root);receipt["lane_dispositions"][1]["transfers"][0]["evidence"][0]["status"]="PASS";dump(root/"agents/relay/parallel/REPLAN-P2.yaml",receipt);self.assertTrue(any("evidence transfer partition" in x for x in parallel_replan(root)[0]))
    def test_new_parallel_plan_and_lanes_must_bind_replan(self):
        with tempfile.TemporaryDirectory() as td:root=Path(td);_,plan,ep1,_=parallel_replan_repo(root);plan.pop("previous_replan");plan.pop("previous_replan_path");dump(root/"agents/relay/parallel/PLAN-P2.yaml",plan);self.assertTrue(any("previous_replan" in x for x in parallel_plan(root)[0]));ep1["identity"].pop("previous_replan");dump(root/"agents/relay/execution-packages/EP-B1.yaml",ep1);self.assertTrue(any("previous_replan" in x for x in parallel_replan(root)[0]))

if __name__=="__main__":unittest.main()
